<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte</name>
   <tag></tag>
   <elementGuidId>f4c84b50-a3f2-4952-af68-0d2440b437af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ea2a2ed4-0aae-4b5b-afca-e179833b57c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>06805901-4791-4ec6-a811-560f38108e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>382a5e56-1796-42e5-8e61-3c70d87e8bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente\ventas.xhtml?nodeTree=Anular / Modificar&amp;codeTree=070102&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3OTExMzM1NCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDY1OThmY2UtNDViMS00YTVjLWEyM2UtNTkwMTQ3YTY1YjkzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.cQktVLC6IKB2Q8G9jBB6TWkU1pfJ13HQvm-l-dapZcw</value>
      <webElementGuid>87748289-24cf-458b-bc77-57e8ceb24760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>35834495-6c7c-4095-ab7a-1579656f1aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>be092282-0761-44d8-9669-3fd505abbd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>c6b78c3e-323d-494b-b8bd-54ac6d1c0919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7a1bfbff-5482-4db2-9431-091c89526697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente\ventas.xhtml?nodeTree=Anular / Modificar&amp;codeTree=070102&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3OTExMzM1NCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDY1OThmY2UtNDViMS00YTVjLWEyM2UtNTkwMTQ3YTY1YjkzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.cQktVLC6IKB2Q8G9jBB6TWkU1pfJ13HQvm-l-dapZcw']</value>
      <webElementGuid>51226274-733b-48a5-9c40-9b753f12e948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
