<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-eye-slash</name>
   <tag></tag>
   <elementGuidId>44df05a5-4aa0-4ccc-88e5-8b91c48c0c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmComprobante:tblComprobante:37:btnBuscar']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>731cdb8b-aae7-4d46-a8a7-7749218c4d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c fa fa-eye-slash</value>
      <webElementGuid>69221580-6545-4728-ac7b-b1bd3832fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmComprobante:tblComprobante:37:btnBuscar&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c fa fa-eye-slash&quot;]</value>
      <webElementGuid>adb935c3-9fd9-41e1-85e2-667dc4eedd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Olva Courier  Datos Personales/Page_Principal - Olva Courier/New Folder/Page_Principal - Olva Courier/ifram</value>
      <webElementGuid>ccdb5be5-f372-479a-a22b-2f6bb45b9095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmComprobante:tblComprobante:37:btnBuscar']/span</value>
      <webElementGuid>ad0fffad-a2e0-4aaf-b939-cb209872db00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[38]/td[15]/button/span</value>
      <webElementGuid>382c599d-b3b8-4072-bf65-bf8a0a5444be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
