<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT. (Boleta)_txt_documento_cliente</name>
   <tag></tag>
   <elementGuidId>14b491ec-86b7-4bf9-9992-88dcb59486e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_documento_cliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebe8cf87-0161-4cb3-912c-8f597335ccf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28238fac-6363-4ece-9cd0-f45c07df2be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>916fbcb7-ebc6-477c-b4b5-4574cb8be082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateDNI()</value>
      <webElementGuid>ae94bfe8-3c9f-4e57-826b-ee69d93a5d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>935ed2a9-d404-41cf-87ab-d85c1fb4d241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e3a9f39b-0b45-429d-83f6-09593ccc692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número</value>
      <webElementGuid>71b62969-9632-4cdf-a0fa-cb35a5f2505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control msg_alert_tt</value>
      <webElementGuid>83399cd1-fbca-48dc-a714-b54f83d2360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>a0605bcd-12eb-4bbe-abed-8d118e4e7d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>491736c6-a8d0-49e3-99a8-ad402901d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>b4b3654e-58b1-4e49-8157-ec36064f64b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12513e65-69bc-40d1-845b-61eaa3d13791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente&quot;)</value>
      <webElementGuid>5b9da1a2-0983-4e36-9bd8-5b48ac9710fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_documento_cliente']</value>
      <webElementGuid>f91fb08c-5dd4-4618-bbda-493bdd761d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/input</value>
      <webElementGuid>8c9239cf-daad-4d30-98b4-d7bf20f71f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e0350845-ed9d-4678-abad-21c5521da1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_documento_cliente' and @placeholder = 'Número' and @title = '.' and @id = 'txt_documento_cliente']</value>
      <webElementGuid>5ca147db-62a7-4768-9e2a-f7949e339ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
