<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reporte_iframePrincipal</name>
   <tag></tag>
   <elementGuidId>3cfc4ca2-3e48-4320-b281-1f8fd55a0084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>66fbb8ce-b0f2-4aca-b4f6-7428f46d8ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframePrincipal</value>
      <webElementGuid>1d10bb97-f8ec-443b-901e-38a171c951f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>0a1e6e4d-1bf1-476b-bb00-643f18514529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OlvaERP-Maestro-web/atencionCliente\ventas.xhtml?nodeTree=Anular / Modificar&amp;codeTree=070102&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3OTExMzM1NCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDY1OThmY2UtNDViMS00YTVjLWEyM2UtNTkwMTQ3YTY1YjkzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.cQktVLC6IKB2Q8G9jBB6TWkU1pfJ13HQvm-l-dapZcw</value>
      <webElementGuid>bd7766a3-07e5-47bc-9110-e009f564d584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframePrincipal&quot;)</value>
      <webElementGuid>04774564-2c68-4d55-85c1-c08f6d80498c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframePrincipal']</value>
      <webElementGuid>f83e98fb-4cd6-4379-9718-295f883b2117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:centerContentPanel']/iframe</value>
      <webElementGuid>b02bf772-47f8-4b74-a1c6-3ec7e54c89f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>72df7fa9-c4c6-4243-bb65-7f2d331f3525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframePrincipal' and @src = '/OlvaERP-Maestro-web/atencionCliente\ventas.xhtml?nodeTree=Anular / Modificar&amp;codeTree=070102&amp;access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aF9zZXJ2ZXJfaWQiXSwidXNlcl9uYW1lIjoiR0FSQ0UiLCJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTY3OTExMzM1NCwiYXV0aG9yaXRpZXMiOlsiQURNSU4iXSwianRpIjoiZDY1OThmY2UtNDViMS00YTVjLWEyM2UtNTkwMTQ3YTY1YjkzIiwiY2xpZW50X2lkIjoiYXV0aG9yaXphdGlvbiJ9.cQktVLC6IKB2Q8G9jBB6TWkU1pfJ13HQvm-l-dapZcw']</value>
      <webElementGuid>f8bc2e1e-6b29-465c-b6a0-e22f2121bf4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
