<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Consulta Envio_iframeConsultaEnvio</name>
   <tag></tag>
   <elementGuidId>db99085e-4e09-4794-91ee-cfd21964bad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeConsultaEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeConsultaEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a6214f00-8ad7-41ea-a007-621b010f5b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeConsultaEnvio</value>
      <webElementGuid>c51bf533-ef9f-4037-9752-85f0643aedc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>8b789eb0-2d9c-4f2f-aca0-2352cb255555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>popup/maestroWeb/consultaEnvio.xhtml</value>
      <webElementGuid>d1ffa401-09fe-4012-847a-edb024002741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeConsultaEnvio&quot;)</value>
      <webElementGuid>aca3b0e3-013f-4561-b5ac-b112caadf548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeConsultaEnvio']</value>
      <webElementGuid>70388549-51f2-4861-8cd9-3fd50a697c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgConsultaEnvio']/div[2]/iframe</value>
      <webElementGuid>f1fd02d0-8d28-4259-9b81-1db4b1225a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>0f0df844-08f2-40c1-8223-bb3f0ea7be33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeConsultaEnvio' and @src = 'popup/maestroWeb/consultaEnvio.xhtml']</value>
      <webElementGuid>b5c19dae-1f02-4776-930f-341d550c73af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
