<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OLVA LINCE - AV. ARENALES 1775</name>
   <tag></tag>
   <elementGuidId>0ab37ad0-27cc-4604-856e-a4f2cda25808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmComprobante:oficina_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2b3b965d-2c4c-4418-93e6-9834db27bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>b55cf004-4a8a-42a2-b890-668dd4d7c171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>09d20627-d454-4980-b486-b0706204027d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3d5c6496-a61e-4a8d-95cb-7730f6e82413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>12cacb79-c9d0-4b0e-be1a-e41163aebebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmComprobante:oficina_4</value>
      <webElementGuid>f202293f-6f27-479c-b071-4cc3f02c270f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>504ca8a6-b491-4933-85f0-8b8819ded638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmComprobante:oficina_4&quot;)</value>
      <webElementGuid>4d40549b-0ff9-4405-8019-cc48dfc28238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>19caad0f-d864-4a88-adbb-1e7e05302673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Olva Courier  Datos Personales/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>f848f019-b189-488f-87bd-fbfaf436dcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmComprobante:oficina_4']</value>
      <webElementGuid>d62447b3-a92a-4c85-bee2-abcaeb1eec41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmComprobante:oficina_items']/li[5]</value>
      <webElementGuid>015c623f-a3d2-4237-8fe5-fbf6addd070d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EX-M.EDUCACION'])[2]/following::li[1]</value>
      <webElementGuid>e62b2720-14f7-4e2a-a661-618278270d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PALACIO JUSTICIA'])[2]/following::li[2]</value>
      <webElementGuid>634f0fb3-d2da-4626-82cf-06b7c570b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA ALMACEN INTERNO -AV. ARGENTINA 4458 CALLAO'])[3]/preceding::li[1]</value>
      <webElementGuid>af8a3a74-7579-4be3-a1aa-bad4ed496f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA SAN ISIDRO - AV. ARAMBURU NO. 978'])[2]/preceding::li[2]</value>
      <webElementGuid>77145402-7a4c-4d4e-a97c-d5335e5879e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/ul/li[5]</value>
      <webElementGuid>483a161b-fc8b-4ed5-a523-70ea36ee7a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmComprobante:oficina_4' and (text() = 'OLVA LINCE - AV. ARENALES 1775' or . = 'OLVA LINCE - AV. ARENALES 1775')]</value>
      <webElementGuid>a848aacc-331c-4e5d-9b11-2358d2e80bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
