<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_nroPreventa</name>
   <tag></tag>
   <elementGuidId>32ab74a4-1c17-489d-bfc7-d7bd1a8f7fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[@id='nroPedido1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nroPedido1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>73bcc455-1ada-458f-8148-7decc0e5ee2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nroPedido1</value>
      <webElementGuid>cc54699d-16e4-4a9e-98c3-2e83c5151dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nroPedido1</value>
      <webElementGuid>93c83c25-db26-445c-ad99-1738fc3d230a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>202406724302</value>
      <webElementGuid>6ab9659c-5d89-4d86-947d-b7a6cae76151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nroPedido1&quot;)</value>
      <webElementGuid>a6839630-d671-4396-ab7c-648d36250840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//b[@id='nroPedido1']</value>
      <webElementGuid>df63b62a-c450-481b-9c6b-48119a473b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/fieldset/div[3]/div/b</value>
      <webElementGuid>cbde253c-b550-495c-af2c-97fc2d81786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aprobado y completado con exito'])[1]/following::b[1]</value>
      <webElementGuid>5edda60c-d551-4220-a91d-7ef856ae9ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha y hora del pedido:'])[1]/preceding::b[1]</value>
      <webElementGuid>c7006d63-0d0c-497c-99f1-e6d5c0a7ddb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='202406724302']/parent::*</value>
      <webElementGuid>aa1275e2-e350-40ce-be37-1c1072638ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>ca3563d1-ee2e-4f12-ba45-04727f9cea46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[@id = 'nroPedido1' and @name = 'nroPedido1' and (text() = '202406724302' or . = '202406724302')]</value>
      <webElementGuid>183aeecc-9f62-41bb-8a9e-59999ce9caa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
