<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VOLVER A INTENTAR</name>
   <tag></tag>
   <elementGuidId>8b2223b9-882d-403c-8506-3617a434067e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-volver_intentar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-volver_intentar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53f0ef28-8180-49db-98d0-358dca865ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-volver_intentar</value>
      <webElementGuid>b261dd68-88d9-401c-8d2a-3604ec9e93f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e4f7504-c208-42f2-9f07-4f8d2b10cddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>c1610e91-e051-4669-ad75-908cff0e1cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VOLVER A INTENTAR</value>
      <webElementGuid>9e768537-fe4c-43ce-b386-82c718dfab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-volver_intentar&quot;)</value>
      <webElementGuid>dddc0e3d-42ec-4360-9f41-d5e8232f19f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-volver_intentar']</value>
      <webElementGuid>13c9df29-c02f-4964-9d25-4a73be8ff7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_pagar']/button</value>
      <webElementGuid>5b5df816-cf15-4c07-82d1-49828f06545d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lo sentimos, no se realizó el pago debido a: Transacción Invalida'])[1]/following::button[1]</value>
      <webElementGuid>3218e5f0-c32f-40dd-8318-58ff73c5425f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::button[1]</value>
      <webElementGuid>63b8cdcf-2c4e-429a-9efb-43454d673a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VOLVER A INTENTAR']/parent::*</value>
      <webElementGuid>2e091bfe-26b2-461b-b7d5-b18bf78dc134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>cb04ba0a-8a3d-4741-843d-eb4b60b3d52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-volver_intentar' and @type = 'button' and (text() = 'VOLVER A INTENTAR' or . = 'VOLVER A INTENTAR')]</value>
      <webElementGuid>2fc3f578-8c35-414e-ae34-b9a8ecbce307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
