<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Acceder para continuar a Olva_frmLogi_81423f (2)</name>
   <tag></tag>
   <elementGuidId>d2e438ab-5746-44b7-9c93-043e79594d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin:loginButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a340d9cd-fc6e-46ee-9991-093c960f5a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin:loginButton</value>
      <webElementGuid>c7b7b52e-8267-40e5-8867-7fb4ef3adbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9f294553-dad1-4b78-8634-691cc2405b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmLogin:loginButton</value>
      <webElementGuid>6f86eb44-6e0c-4db2-95a8-50baf404a99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Acceder </value>
      <webElementGuid>254b9440-a6d9-46f7-8bb8-6808a1d0dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin:loginButton&quot;)</value>
      <webElementGuid>794e2cbb-34ce-4dc5-9cdc-b2af4064deac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin:loginButton']</value>
      <webElementGuid>64db337f-5a16-4fa4-9459-eb845bd330e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin:pnlLogin_content']/table/tbody/tr[3]/td/input</value>
      <webElementGuid>177e291f-0472-43ec-94fd-688023470d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>a84b1792-4b9e-4991-9ec5-4505aa7d2ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin:loginButton' and @type = 'submit' and @name = 'frmLogin:loginButton']</value>
      <webElementGuid>83ab5b86-9b94-4e04-b87f-cdf4baea9c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
