<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Acceder para continuar a Olva_frmLogi_dbfc6f (2)</name>
   <tag></tag>
   <elementGuidId>4c56fec4-cbee-467b-a022-f732574143e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin:txtClave']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2d5247b-df66-4fc7-b83b-38541ffbe843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin:txtClave</value>
      <webElementGuid>e6178dd6-5ee0-4c46-8182-0932cc8dbfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmLogin:txtClave</value>
      <webElementGuid>3330d068-596f-482b-a9fe-c8d4ebc7e20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7cba616e-3feb-499f-b9c2-bfb12ef31eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-password ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>b9e57ea3-a369-4949-a324-1b7e45405cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>clave</value>
      <webElementGuid>95e033c2-e9d1-4ae7-9468-441e6535a413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e231ad39-e31b-4161-9fa7-6663ec691790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47ae5850-557e-43bd-a520-05c6be6032c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b8f4526-27cd-478e-aead-43af79f64526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin:txtClave&quot;)</value>
      <webElementGuid>fe218551-2412-421a-a9d6-8e68c9e89b17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin:txtClave']</value>
      <webElementGuid>4a4fd2d8-1567-4f79-aa79-e313f0045213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin:pnlLogin_content']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>151cf8c0-bdad-4128-b040-8c977ba2424a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>d7fb476c-6e20-4d58-a8e7-d8e0385481cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin:txtClave' and @name = 'frmLogin:txtClave' and @type = 'password' and @placeholder = 'clave']</value>
      <webElementGuid>8cbc5ff3-b38e-4117-b3fd-3679041af636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
