<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR (2)</name>
   <tag></tag>
   <elementGuidId>eb5569aa-7cf8-4728-a672-fb8be4bb0154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_aceptar_tipo_envio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_aceptar_tipo_envio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>308c04e0-ef2c-4a93-b92f-29df33e5e599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_aceptar_tipo_envio</value>
      <webElementGuid>41bee872-7411-4dbc-97db-0bf3dfed039b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e77650f9-fb3d-47f4-abdc-39d33380cbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>3d4caa9c-969e-4ed8-bdc8-4d902bd18e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>5a3c633b-258b-4f2b-9aa2-6ea2b763c070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_aceptar_tipo_envio&quot;)</value>
      <webElementGuid>95d63c6f-0b75-47dd-bb47-772777649901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_aceptar_tipo_envio']</value>
      <webElementGuid>35a96769-380e-4828-9d5c-341a115fe5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/button</value>
      <webElementGuid>487d030c-e1c0-4e31-865e-d215ecc17405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS DE TARJETAS, AGENDAS Y CAJAS NAVIDEÑAS'])[1]/preceding::button[2]</value>
      <webElementGuid>6bfc4185-eb98-4908-9de4-c4f2452196a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUAR']/parent::*</value>
      <webElementGuid>87a935df-8fdd-4692-8e4d-c083ef8981ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>73964638-240b-41b0-9b94-6bd9903a2c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_aceptar_tipo_envio' and @type = 'button' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>96e5eed7-9a01-42b0-ba75-fe0dc4d22dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
