<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de cajas o paquetescon un peso mxi_37770f</name>
   <tag></tag>
   <elementGuidId>ca31fa01-dafd-4efb-ab4d-0e77e42f0811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_sobre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_sobre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5a036a65-c706-46eb-92bc-efc416e14a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_sobre</value>
      <webElementGuid>819622e4-d3af-47c4-9328-c319aedec177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png</value>
      <webElementGuid>2246a5c9-2421-4508-91e4-d049adaab6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>b175fa3f-1ed2-482a-a997-8c2130877125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>3afa2f0a-3d53-4eac-a62d-67c7e6d83670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>f72e4b42-050f-4af3-8465-b7b9b7752b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_sobre&quot;)</value>
      <webElementGuid>fd24496f-76e7-4b36-8128-b65603b55ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_sobre']</value>
      <webElementGuid>85ab437f-f4a7-4c3a-8a7b-8e333b332133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_sobre']/img</value>
      <webElementGuid>0e8f5f70-93c7-4366-8e4c-6dedb6ca58a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN PAQUETE'])[1]/following::img[1]</value>
      <webElementGuid>f65b5214-c018-4659-b95a-c05995d0a9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN SOBRE'])[1]/preceding::img[1]</value>
      <webElementGuid>b7d12b18-c670-4ec0-ab19-a03413c56953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png')]</value>
      <webElementGuid>2884e783-0cb1-45c3-8b0e-efe40828fa6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/div/figure/img</value>
      <webElementGuid>74adc8b0-860d-484a-9def-1f2fd0387830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_sobre' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png']</value>
      <webElementGuid>e3aadc93-3796-4e89-a8b5-0685563ab519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
