<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de documentoscon un peso mximo de__8aba39</name>
   <tag></tag>
   <elementGuidId>a05fcd1b-fe07-44d2-bb6d-964de2e9be16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_caja</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_caja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f84e589-f1af-4a27-bdb8-39c1ede0778b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_caja</value>
      <webElementGuid>fe789223-6ae4-4cde-8e64-5abdad5731f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png</value>
      <webElementGuid>1b855044-631b-4d64-a842-3a9de0e257ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>d4407312-1c70-4573-bfa9-dbd145ad2318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>12df889c-a6ba-4da6-8807-1190d2a21b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>c2ce3163-d22f-4ad5-8581-9030c2032f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_caja&quot;)</value>
      <webElementGuid>9b0d4882-1a55-4658-8d0d-3c4cd2db2dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_caja']</value>
      <webElementGuid>d9ad2ed2-e8e1-4e05-862a-fbc87b61c233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_caja']/img</value>
      <webElementGuid>819ddac1-36ad-450c-9cb0-a77066c36bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png')]</value>
      <webElementGuid>c23389f7-7fc4-479e-bfb8-95c3fd97b03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div/figure/img</value>
      <webElementGuid>c0fdf6b3-df10-450f-bb42-17e3c102c894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_caja' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png']</value>
      <webElementGuid>6c83ce20-7dd8-4392-8cde-7849859c071f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
