<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_He ledo y acepto los_checkmark</name>
   <tag></tag>
   <elementGuidId>a8a68f53-b7be-4ff3-a995-883b1c12bc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_tipo_envio']/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2375b5c3-6499-4d0e-a8f4-8b694cf69951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>a5caf1a6-552c-4349-a4b5-5709ffee01d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tipo_envio&quot;)/p[@class=&quot;terms&quot;]/label[@class=&quot;container-check&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>24f68074-eafd-402c-9087-3fc27b671269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/span</value>
      <webElementGuid>7b8929ff-281e-4024-8b40-10ae6bd7232a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>819d0acf-a8eb-47fa-88c0-ab51c53cbb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
