<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_He ledo y acepto los_checkmark (2)</name>
   <tag></tag>
   <elementGuidId>45c3beef-893c-4e06-af0a-b92cce004d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_tipo_envio']/p/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>388d9a0b-d20e-47aa-9ca7-ba62bb6ded1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>283e84fd-0f4c-4e3c-9b76-3a4a84b3a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tipo_envio&quot;)/p[@class=&quot;terms&quot;]/label[@class=&quot;container-check&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>bc3912ed-fe4d-4e6c-8935-6a493993edc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/span</value>
      <webElementGuid>85a33529-3e55-41b1-9ff5-716e9b33f07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::span[1]</value>
      <webElementGuid>91372e67-0b2e-42d3-9b50-fa0d19f2292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>4b5c8e06-b322-446f-9cfe-dbb9e6594e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
