<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_Aceptar</name>
   <tag></tag>
   <elementGuidId>c6cbb3f1-1516-4833-803b-1a26945594a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonAceptarClave']/h3/center</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonAceptarClave > h3 > center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>10858cea-81da-44dc-a1b5-9849460a3768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>f7d2aecf-e2e8-4f09-939d-6cd107256599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonAceptarClave&quot;)/h3[1]/center[1]</value>
      <webElementGuid>a4f9acb9-386f-4209-99c7-ddb8db126f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttonAceptarClave']/h3/center</value>
      <webElementGuid>2c1cea2f-27fd-420c-a8eb-c75ca9f8f18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envía la clave de seguridad a la persona que vaa recoger el envío.'])[1]/following::center[1]</value>
      <webElementGuid>47f63ae9-4cea-4761-a0d7-1c7c8c810e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡IMPORTANTE!'])[1]/following::center[2]</value>
      <webElementGuid>7999a35b-4e33-4246-bed2-6222eece975b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/preceding::center[1]</value>
      <webElementGuid>908bbdb4-87af-4ed3-aa4d-6821a2ad6242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3/center</value>
      <webElementGuid>22bfc2f4-51ba-4343-b230-806df5ced8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>7c3d0d06-2bce-48a8-9f54-cab4ab24132e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
