<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_trminos de uso y polticas de privacidad (1)</name>
   <tag></tag>
   <elementGuidId>7fafb3c5-1049-419f-bc4a-b13ab7e2a655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='verTerminos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verTerminos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>082098aa-6f4a-4add-bd9b-7a83af9343bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verTerminos</value>
      <webElementGuid>2073d0b7-258c-4b75-ad57-c6ed1fbfa58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6e93b748-cfd1-4604-9303-7c00e0172286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>términos de uso y políticas de privacidad</value>
      <webElementGuid>f5058532-e75e-4deb-9d01-a98f8f2f478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verTerminos&quot;)</value>
      <webElementGuid>19e35787-01d8-476f-bba4-e016cb09501f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='verTerminos']</value>
      <webElementGuid>86a073ef-cd0d-4ab5-a7cb-e1d6ea27028d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/a</value>
      <webElementGuid>5056e5ea-880b-4e2c-8d6f-db99be5da5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'términos de uso y políticas de privacidad')]</value>
      <webElementGuid>b705221b-da59-44ba-8bea-7b01f9832815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::a[1]</value>
      <webElementGuid>11a777ec-6161-434a-8933-665c5ee805b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='términos de uso y políticas de privacidad']/parent::*</value>
      <webElementGuid>fa9d29cf-d42e-4fbe-8752-ee4eba2aa76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>017c5411-7cd0-4fa4-b35c-55706cad0b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>b06ada47-0b25-40c6-a01c-ad78f0281a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'verTerminos' and @href = '#' and (text() = 'términos de uso y políticas de privacidad' or . = 'términos de uso y políticas de privacidad')]</value>
      <webElementGuid>d5ae9b4d-91bc-4837-a442-826de1a51002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
