<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Qu deseas realizar hoy_img_paquete</name>
   <tag></tag>
   <elementGuidId>a1cb98c1-e5de-495c-ad7b-ba6f8da20537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_paquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_paquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e47e689d-338a-48a2-a539-26fb3a4090a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_paquete</value>
      <webElementGuid>e5e65acd-573a-496a-833e-586021527632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png</value>
      <webElementGuid>172bf6c2-10fe-4c92-aa8d-800fe302bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>63b241cc-6590-409f-9c16-1d4a25ccc03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>f037363c-75b4-4e9e-9b6f-c042d287470e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>3c0dd6dc-4b8f-4640-a95e-718f1d5fae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_paquete&quot;)</value>
      <webElementGuid>c75ad586-b101-49bd-9196-7b31c61bad7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_paquete']</value>
      <webElementGuid>87a2f074-ac1b-4a9a-a626-3524aa2c4885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_paquete']/img</value>
      <webElementGuid>f6220461-fc51-4dca-b007-dc7a9e14c1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/following::img[1]</value>
      <webElementGuid>23d1c8f3-72fd-445b-8212-c9b3a27c254b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::img[1]</value>
      <webElementGuid>a16a21ec-3d53-4cf6-bf39-0d60628c5224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN PAQUETE'])[1]/preceding::img[1]</value>
      <webElementGuid>2a0d8983-ca42-411b-8d09-87675f8796fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png')]</value>
      <webElementGuid>943cfacb-d39c-430c-8559-d01ae7b5ff19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>86e06e2f-cd0c-4bd2-a709-901cbcaea25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_paquete' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png']</value>
      <webElementGuid>bbcadc5c-5a6c-460c-9bfe-c4c81054284b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
