<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu deseas realizar hoy_radioTipoEnvio</name>
   <tag></tag>
   <elementGuidId>8eb945e9-cc3f-4906-b110-c2b0706c78d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ced55162-4898-4c68-88e6-d1d184ed3d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>53052825-0f14-42d1-9f9b-c7c9521d79f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioTipoEnvio</value>
      <webElementGuid>137de4c6-b8e4-40b8-9064-7ad3d3678b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtn_paquete</value>
      <webElementGuid>9093498e-dc55-455b-ab92-fc392c19537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paquete</value>
      <webElementGuid>23ca2456-7a6f-4750-b0d2-70d1b99a1f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdtipoEnvio</value>
      <webElementGuid>fa240c2c-390a-423d-8c4d-8dce84274063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paquete&quot;)</value>
      <webElementGuid>7521a97f-0d47-4cee-9276-c38ba3d456ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paquete']</value>
      <webElementGuid>68eaa381-062f-459d-b95a-6c0b568db2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/div/ul/li/label/input</value>
      <webElementGuid>cae826c4-fde8-4235-9c52-6c56c75d34ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>22a91d3b-c829-4b42-8c33-0453eba1945d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radioTipoEnvio' and @id = 'paquete']</value>
      <webElementGuid>50c88b5c-3033-4dcc-9724-b61dc962906a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
