<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu deseas realizar hoy_radioTipoEnvio (1)</name>
   <tag></tag>
   <elementGuidId>3f9b563c-7226-46ca-ba2c-0b241f8e52ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca729ab-8caa-4c94-9a2c-4007c928939e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>455415f5-11e1-437a-854f-3867d9ac4ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioTipoEnvio</value>
      <webElementGuid>20d9e870-3bb3-4660-bd1a-607cc9fc3bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbtn_paquete</value>
      <webElementGuid>b5ff6c2c-dceb-445d-8e61-31d9eb8fd0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paquete</value>
      <webElementGuid>7dd28e1f-ddb3-4713-81be-86fb4449bfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdtipoEnvio</value>
      <webElementGuid>8b4fa3b8-b3e9-4038-85f7-acd50ac84295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paquete&quot;)</value>
      <webElementGuid>f3117f21-61e1-4706-bdfa-ba9f32e76df2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paquete']</value>
      <webElementGuid>c8627d28-dba0-462c-8aff-a8ed7d99b8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/div/ul/li/label/input</value>
      <webElementGuid>b29eca63-dd9f-4c5b-a70a-35f2a2a400b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>29021602-d04e-4764-ac19-1c11c5a5be6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radioTipoEnvio' and @id = 'paquete']</value>
      <webElementGuid>73337037-01a9-4a3a-8b59-fc8ce348df27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
