<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aceptar_visaNetJS</name>
   <tag></tag>
   <elementGuidId>9f07dc96-2c9a-4c20-aa9f-a31c9cb93a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visaNetJS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visaNetJS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1b3078d1-3fd9-4497-b235-34c4cc2e334d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaNetJS</value>
      <webElementGuid>53a7b62a-0316-4cad-84e8-b93ab4bff0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1a83ae9-5909-4dc1-a31d-e363899a840e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b01fe66-4276-4172-b3df-cedcabaa78e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-content-qas.vnforapps.com/v2/visanet.html?0.4774494152612687&amp;qa=true</value>
      <webElementGuid>15102fce-3a01-4eca-a1a3-7550406e1402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaNetJS&quot;)</value>
      <webElementGuid>795315d3-1fc0-4f78-a4b0-d4d13431ceac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visaNetJS']</value>
      <webElementGuid>ae24407e-f105-4800-88de-1f05fa498b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visaNetWrapper']/iframe</value>
      <webElementGuid>5c6652c0-55ec-470d-86a1-5c258e441a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>535c890c-1bd6-449a-b08f-873302a2e51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visaNetJS' and @src = 'https://static-content-qas.vnforapps.com/v2/visanet.html?0.4774494152612687&amp;qa=true']</value>
      <webElementGuid>da82114b-dc05-421f-b141-8e155d5250da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
