<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_S 14.93</name>
   <tag></tag>
   <elementGuidId>645f5af5-bf98-4af4-8d80-a93699341a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='txt_total']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9ab5ba3c-cd7e-4867-99ab-e0bb70755202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>ea2ab60c-8585-47a6-958f-8126fcfdb62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>49d7a0c8-9e28-4294-b6be-bf124339ed73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>e64f1a52-7642-45b8-b3f1-c8342ddd20e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S/ 14.93</value>
      <webElementGuid>c0f2f807-25a8-4a6d-954a-3f86e4b3ebb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_total&quot;)</value>
      <webElementGuid>135b1374-72e0-4d5e-bdd9-184b6dc1520e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='txt_total']</value>
      <webElementGuid>ab648aa7-17ec-4df4-9d27-e168a162f307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso3']/div[2]/div[3]/div/table/tbody/tr[10]/td[2]</value>
      <webElementGuid>31773e64-17a2-455c-a052-22fe1d8fb781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::td[1]</value>
      <webElementGuid>7df687c8-6ceb-425c-bf7f-52c86ac43b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 2.28'])[1]/following::td[2]</value>
      <webElementGuid>5e78b9c6-14ee-4d69-b866-2da67fcddd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recojo en tienda'])[1]/preceding::td[1]</value>
      <webElementGuid>5e093414-cab9-4981-923e-56987316b0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA - LIMA - SANTIAGO DE SURCO'])[1]/preceding::td[1]</value>
      <webElementGuid>f661a80d-25b6-48d1-b8d1-dbec6e565548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S/ 14.93']/parent::*</value>
      <webElementGuid>ccee38d7-3373-4d6a-82d8-b91a630c2743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]</value>
      <webElementGuid>0f013ca8-146d-40b9-a188-26339df7cb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'txt_total' and @name = 'txt_total' and (text() = 'S/ 14.93' or . = 'S/ 14.93')]</value>
      <webElementGuid>bd7dc2e0-7d72-4b3c-b158-9da6c93ecdb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
