<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_total detalle</name>
   <tag></tag>
   <elementGuidId>95f5d68c-8d19-493f-977f-6a1f2be40be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmDetalleComprobante:j_idt102&quot;]/tbody/tr[5]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d376f599-c8e7-42d9-b780-4418ca06a0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>d05ba109-c111-4820-876d-3bc6263edaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>fd301eec-2a2a-4073-bd67-2df6cce81dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>fe8f08da-c626-4e42-8ae9-d0f7f9016f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S/ 14.93</value>
      <webElementGuid>1faa7886-d14a-47eb-b30c-579ac4c8d2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_total&quot;)</value>
      <webElementGuid>28fdd350-a811-4405-9446-ccab72c6793c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='txt_total']</value>
      <webElementGuid>9a98cbd3-6b7f-4220-b005-c27ac863f287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso3']/div[2]/div[3]/div/table/tbody/tr[10]/td[2]</value>
      <webElementGuid>02b4d5da-8464-45b4-9876-3a0abac0031f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::td[1]</value>
      <webElementGuid>09e22e84-a7ce-4725-b915-9b6ceefad443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 2.28'])[1]/following::td[2]</value>
      <webElementGuid>e2fceb30-a9eb-4cba-ad5d-dafcdbd57743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recojo en tienda'])[1]/preceding::td[1]</value>
      <webElementGuid>07ef887c-72cc-4957-9d20-913f37c39a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA - LIMA - SANTIAGO DE SURCO'])[1]/preceding::td[1]</value>
      <webElementGuid>c3c30067-4dfb-4ae6-89d0-eba872ce0e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S/ 14.93']/parent::*</value>
      <webElementGuid>f63fcc0f-b86f-4524-8838-e2ae13e0018c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]</value>
      <webElementGuid>e8cf9f52-2127-45bd-a158-cfd145dd49a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'txt_total' and @name = 'txt_total' and (text() = 'S/ 14.93' or . = 'S/ 14.93')]</value>
      <webElementGuid>078eecc6-5d2d-4a57-b910-540692cf8302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
