<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de cajas o paquetescon un peso mxi_37770f</name>
   <tag></tag>
   <elementGuidId>703af583-7eca-4115-a6e4-aabbe4cf415c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_sobre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_sobre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>953ceb8f-201f-40cd-b173-0abce3e9e5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_sobre</value>
      <webElementGuid>847a0f56-7887-4639-94e2-08e3f45eefc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png</value>
      <webElementGuid>92208784-c404-4b74-9dda-9181d58560ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4a0ccaad-aad1-4f8a-8032-85db239e31d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>38f808c7-e67e-48a0-8e62-b8054354cf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>b62f5dde-6b71-4857-aac8-2fc09465a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_sobre&quot;)</value>
      <webElementGuid>52c10ce4-7332-4f6f-adc9-dca2d531a6d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_sobre']</value>
      <webElementGuid>f92d25e3-6d86-4581-a422-3e8406ddabf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_sobre']/img</value>
      <webElementGuid>13ad759a-b8a2-4196-9325-dfd196968229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN PAQUETE'])[1]/following::img[1]</value>
      <webElementGuid>bb346132-9615-493d-9122-792f969177fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN SOBRE'])[1]/preceding::img[1]</value>
      <webElementGuid>443d4b28-2c09-45e9-bfd8-6c33bf0d59ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png')]</value>
      <webElementGuid>9c593bb3-45ca-488e-ba33-1f6d2481cfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/div/figure/img</value>
      <webElementGuid>fb929645-b03f-4b7e-86c4-54a86f629708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_sobre' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png']</value>
      <webElementGuid>ef65641a-dfc1-4a7c-813d-fddb408d4dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
