<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Consulta Envio_iframeConsultaEnvio</name>
   <tag></tag>
   <elementGuidId>b92a3308-b9a4-4f41-9a95-4b35fbc540b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeConsultaEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeConsultaEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>34d7fd22-0439-4179-a3d4-0a9d13fefef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeConsultaEnvio</value>
      <webElementGuid>2dbf9770-880b-4fb1-b148-9f44b35c2270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>25e7f7f0-85d4-4344-8c4d-736639037d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>popup/maestroWeb/consultaEnvio.xhtml</value>
      <webElementGuid>337c4b49-9df5-4d6d-9f1b-e515fc1e09b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeConsultaEnvio&quot;)</value>
      <webElementGuid>4670f4e9-e940-43fd-b37d-e9ad89ba7dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeConsultaEnvio']</value>
      <webElementGuid>c8b03557-26d1-4819-9204-9efdc71cb93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgConsultaEnvio']/div[2]/iframe</value>
      <webElementGuid>5b579ab4-06f6-4c45-9527-1effddc375bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>f4df4f95-53f6-4594-888b-59f26badd6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeConsultaEnvio' and @src = 'popup/maestroWeb/consultaEnvio.xhtml']</value>
      <webElementGuid>92ef2fec-70f7-4a4f-816d-fa0ddb0af338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
