<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OLVA LINCE - AV. ARENALES 1775</name>
   <tag></tag>
   <elementGuidId>7647555e-0d8a-4769-9ffc-21a97328904f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmComprobante:oficina_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>375d2e85-54a0-4c33-9977-7b8170c7cddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>03b983c0-a138-4775-b855-79097de2f97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>cac319e9-8578-4281-b880-a8422f345119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f187be6b-e120-4284-8b05-115716fd20aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cf06993b-fa84-4ec4-8d88-7b2850d72435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmComprobante:oficina_4</value>
      <webElementGuid>62485aec-8637-41ae-93cb-c4d9d2c19575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>9335a4b1-1e57-43e2-b85b-ed333bb0e058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmComprobante:oficina_4&quot;)</value>
      <webElementGuid>f11ec7cb-813a-49aa-9ac2-505792b1b59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>bcfe66f5-fafe-409a-9867-691e7eea7292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmComprobante:oficina_4']</value>
      <webElementGuid>3110da89-0dde-4df2-9e5b-bcf2d272e0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmComprobante:oficina_items']/li[5]</value>
      <webElementGuid>4cf7a120-7020-40bb-9904-7d6e3fd08a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EX-M.EDUCACION'])[2]/following::li[1]</value>
      <webElementGuid>55457798-2457-440b-9450-7793ea80134c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PALACIO JUSTICIA'])[2]/following::li[2]</value>
      <webElementGuid>d5869e9e-3bfc-44da-b2ae-17ad196dabc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA ALMACEN INTERNO -AV. ARGENTINA 4458 CALLAO'])[3]/preceding::li[1]</value>
      <webElementGuid>8c0f3e02-9872-4665-a2ba-254b5062e6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA SAN ISIDRO - AV. ARAMBURU NO. 978'])[2]/preceding::li[2]</value>
      <webElementGuid>3e9a94cd-759d-4214-ba3b-3b1e3ed30dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/ul/li[5]</value>
      <webElementGuid>31cb23d7-4a03-4bcc-992e-5a76565d883b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmComprobante:oficina_4' and (text() = 'OLVA LINCE - AV. ARENALES 1775' or . = 'OLVA LINCE - AV. ARENALES 1775')]</value>
      <webElementGuid>49e6855f-51d0-4629-b0d6-4bd9935540dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
