<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monto_embalaje</name>
   <tag></tag>
   <elementGuidId>d37ab53e-34d2-4187-a73e-f8544ff499ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmConsultaEnvio:panelEnvio:embalaje']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27702bab-10a3-41a4-82cb-836e97ef8e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConsultaEnvio:panelEnvio:embalaje</value>
      <webElementGuid>6b1df39a-a534-4a96-98c6-2056d675c059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>dbd59b70-3181-4e2e-8edc-10e0ac62eb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConsultaEnvio:panelEnvio:embalaje&quot;)</value>
      <webElementGuid>8685ca25-246d-403e-a862-cf134123199e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>2a4a78d4-f3f5-4166-92a3-54beb0fd16e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>8abcd24a-d882-4b01-976d-12dc6dae60cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>6ab892d4-8603-4e48-8c84-26af211246bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmConsultaEnvio:panelEnvio:embalaje']</value>
      <webElementGuid>74edafe1-d170-4669-9ac2-1dbc5b9472bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='frmConsultaEnvio:panelEnvio:j_idt385']/div/table/tbody/tr/td[9]/span</value>
      <webElementGuid>108bcad8-fac2-4562-9c1d-cce1c0957466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[3]/following::span[1]</value>
      <webElementGuid>c8418e27-4196-4b7a-84fa-df52f82e3ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMBALAJE:'])[1]/following::span[2]</value>
      <webElementGuid>131236a1-1d7f-45ec-b339-00cb54554158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTROS:'])[1]/preceding::span[1]</value>
      <webElementGuid>9d085575-9eb8-4ac5-9c2d-7d3477f1b3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[4]/preceding::span[1]</value>
      <webElementGuid>1d00204c-27ea-44b4-9c0f-f30ac39363a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/table/tbody/tr/td[9]/span</value>
      <webElementGuid>07fddc35-8cf2-4e19-978e-6b19ff6c9a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmConsultaEnvio:panelEnvio:embalaje' and (text() = '0,00' or . = '0,00')]</value>
      <webElementGuid>6dea0e43-b1ce-42f7-a579-49c310da55b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
