<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Venta</name>
   <tag></tag>
   <elementGuidId>c38b5233-f16c-4295-8794-6004405cde65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3034bfb9-0eed-42af-ba66-724127021910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPrincipal:tree:0_0_2:lblNode</value>
      <webElementGuid>d869a3ae-33ff-4892-a512-2c8faf6eae0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>cf1cf886-50fe-4c3a-b441-f5e14276b1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venta</value>
      <webElementGuid>bddeaa56-91a8-4272-a23e-91afd91c9bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPrincipal:tree:0_0_2:lblNode&quot;)</value>
      <webElementGuid>3f527e2b-ab6b-4231-a47b-c163df672ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmPrincipal:tree:0_0_2:lblNode']</value>
      <webElementGuid>4f0b9d77-1fcd-4b15-b44a-73703a194717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='frmPrincipal:tree:0_0_2']/span/span[3]/span</value>
      <webElementGuid>d7dfac9b-9fe4-4895-9c62-3516ea0c8da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte'])[1]/following::span[5]</value>
      <webElementGuid>12f4387d-1641-4b76-b7bb-5f4705a29fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anular / Modificar'])[1]/following::span[10]</value>
      <webElementGuid>e914adc4-550f-4abd-870b-01c3eaa6dda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota Credito / Debito'])[1]/preceding::span[3]</value>
      <webElementGuid>e082a7bf-ac24-4bee-aeb7-f8e952729a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edicion Tracking'])[1]/preceding::span[8]</value>
      <webElementGuid>6c71fda8-8375-4fa1-8381-ed19c55a60e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/ul/li[3]/span/span[3]/span</value>
      <webElementGuid>5db5b585-7fcd-40ed-a9ff-932b90997654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmPrincipal:tree:0_0_2:lblNode' and @title = 'Venta' and (text() = 'Venta' or . = 'Venta')]</value>
      <webElementGuid>944cfcc9-dcc3-43c2-8676-714d104716f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
