<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 2Kg</name>
   <tag></tag>
   <elementGuidId>fc614bbc-4fa9-4389-89f0-a39f6777b9b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b848507-1e6b-4055-b25d-d4c4678b2c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow ml-10 mr-10</value>
      <webElementGuid>7a9d6c77-05aa-4f01-b1fd-6c5a8f37a975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_2</value>
      <webElementGuid>99982cd9-96f7-469f-af49-5bdb63ba0019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 2Kg</value>
      <webElementGuid>a317e98b-22d1-4f81-ba9e-9835d3238098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_2&quot;)</value>
      <webElementGuid>96a09e37-a85a-42cb-88f9-8705a85b689b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_2']</value>
      <webElementGuid>6c926395-b34b-49be-9bec-fbff37e5ed08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[3]</value>
      <webElementGuid>c276bf59-465b-4591-a2b3-c06c2462b2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::div[5]</value>
      <webElementGuid>83da06e2-b23e-4576-8901-2e78c7a8fadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>051e16c1-e0ad-464a-8527-eaaf6d1c201e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_2' and (text() = 'Hasta 2Kg' or . = 'Hasta 2Kg')]</value>
      <webElementGuid>58e82fe0-664f-4f0d-b0eb-a9ccaf7b7cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
