<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_REGISTRO DE ENVOS_fa fa-home pd-2</name>
   <tag></tag>
   <elementGuidId>445cdbe8-77ef-4ae5-9b0b-3039f2c6110e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-home.pd-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clear_session']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>896819aa-e3e1-4de7-b3df-bb0362292d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home pd-2</value>
      <webElementGuid>af78d775-eacf-4d92-b94b-a3492b918f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clear_session&quot;)/i[@class=&quot;fa fa-home pd-2&quot;]</value>
      <webElementGuid>d945a194-2d75-4d19-830a-3f2bf8699692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='clear_session']/i</value>
      <webElementGuid>e92c1b66-385a-40f8-912b-9fdf36c99017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>edffd36c-753a-45ed-a01e-039a6172afc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
