<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inicio (1)</name>
   <tag></tag>
   <elementGuidId>9f444d58-4119-4ae4-90a3-2de64e3ef5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.visible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clear_session']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adfe11d8-5193-4e79-8556-3946b2f3cb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>visible</value>
      <webElementGuid>bed37b23-ebba-4ca3-acb3-8331271a647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio</value>
      <webElementGuid>d25f0989-4cc4-43c8-99fb-ff9972c22a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clear_session&quot;)/span[@class=&quot;visible&quot;]</value>
      <webElementGuid>89019a55-6054-45c3-9aa0-1b2bc6cc02c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='clear_session']/span</value>
      <webElementGuid>ad23daf1-caa9-4d30-aa47-fd5f80f5b76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRO DE ENVÍOS'])[1]/following::span[1]</value>
      <webElementGuid>07f92eeb-8dd8-4504-b668-2d0f218e4232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/preceding::span[1]</value>
      <webElementGuid>b15494d1-8bb0-4bda-a9fe-d7109ae92824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando...'])[1]/preceding::span[2]</value>
      <webElementGuid>9a0a2e55-016e-4bc6-8dd8-5d0ed68437e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inicio']/parent::*</value>
      <webElementGuid>841d5c1b-ee35-4943-abac-37e645e934e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>e684fd85-e696-47ca-96dd-fb27ebf7c052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Inicio' or . = ' Inicio')]</value>
      <webElementGuid>7c891245-2ee5-462d-ac65-1215553d0055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
