<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inicio (2)</name>
   <tag></tag>
   <elementGuidId>d0d8a31c-0625-4fc9-89a2-fe8fb1fbf550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.visible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clear_session']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>278f6db1-3843-482d-bc9f-71802e1fd1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>visible</value>
      <webElementGuid>69ecfbbb-8b3c-4006-9a33-c8332ca815ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio</value>
      <webElementGuid>3a61999a-b791-48c3-aac9-ff186d970660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clear_session&quot;)/span[@class=&quot;visible&quot;]</value>
      <webElementGuid>d14d107d-1f69-4588-9c55-cb84fce82150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='clear_session']/span</value>
      <webElementGuid>c9849d31-8df0-4d5b-ba72-12a1f079a591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRO DE ENVÍOS'])[1]/following::span[1]</value>
      <webElementGuid>3631ec0b-c79d-41fa-8581-d8d04e8d29e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/preceding::span[1]</value>
      <webElementGuid>c6840e14-2cb9-420b-b2a3-385803bde9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando...'])[1]/preceding::span[2]</value>
      <webElementGuid>109626b8-8afc-411d-94ad-32b01d964410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inicio']/parent::*</value>
      <webElementGuid>1669e178-62ba-4574-acc8-4067d6f6b8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>fc461751-6fa2-4610-9b5a-6ae1b3a1ea73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Inicio' or . = ' Inicio')]</value>
      <webElementGuid>22dc146f-bd39-482b-8fbd-e88e06536229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
