<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Consulta Envio_iframeConsultaEnvio</name>
   <tag></tag>
   <elementGuidId>c82e26f1-1e28-4e07-b76e-2e1f3674b98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframeConsultaEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframeConsultaEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>117c71d5-b4b9-495a-9a9e-cd67cd88eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeConsultaEnvio</value>
      <webElementGuid>58abc95b-3134-4d07-99d7-27b31fed6a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget ui-widget-content ui-corner-all iframeLayoutCenter</value>
      <webElementGuid>c07800ff-ac80-451c-9bc2-4a6043094dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>popup/maestroWeb/consultaEnvio.xhtml</value>
      <webElementGuid>b0ccd3fd-ae80-46e0-b2a2-4a0ee6e0982f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframeConsultaEnvio&quot;)</value>
      <webElementGuid>1d168d05-ac12-4587-8145-c8a06ea215ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframeConsultaEnvio']</value>
      <webElementGuid>41ba6a9c-a244-4ff4-8fb5-828fb94c5f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgConsultaEnvio']/div[2]/iframe</value>
      <webElementGuid>3d0a5697-bf5f-4fe4-9116-eba1b587e87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>b3a48e15-85c0-4179-8eba-2a3bd4f132aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframeConsultaEnvio' and @src = 'popup/maestroWeb/consultaEnvio.xhtml']</value>
      <webElementGuid>f6eace70-cb7c-4899-835c-33416ccd5e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
