<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Montos</name>
   <tag></tag>
   <elementGuidId>1d33baed-09f2-4938-9c7c-38381ee9c4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//legend[@class='ui-fieldset-legend ui-corner-all ui-state-default ui-state-focus ui-state-hover'][contains(.,'Montos')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>legend.ui-fieldset-legend.ui-corner-all.ui-state-default.ui-state-hover.ui-state-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>0fb6bd27-ff04-4d37-a2c8-0151e6915c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-fieldset-legend ui-corner-all ui-state-default ui-state-hover ui-state-focus</value>
      <webElementGuid>60f0755c-9bac-4a5c-b7a8-a77a85a3f3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbfb596e-cef1-499c-8cdb-cacbbe93d1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50e601b5-fd7b-4c26-842f-89a71a276073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Montos</value>
      <webElementGuid>10d62e9b-6a62-40cd-8e31-83af78992fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConsultaEnvio:panelEnvio:j_idt385&quot;)/legend[@class=&quot;ui-fieldset-legend ui-corner-all ui-state-default ui-state-hover ui-state-focus&quot;]</value>
      <webElementGuid>61b521c3-bf61-4f42-ad2d-ea3286c0ef8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>c83e0322-08e6-4e30-837b-1fe2b1e71cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='frmConsultaEnvio:panelEnvio:j_idt385']/legend</value>
      <webElementGuid>30ab8e58-a243-4da9-9af9-c7cd051ab07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articulo Contenedor'])[1]/following::legend[1]</value>
      <webElementGuid>4c8c496d-3de0-4e27-8c40-7f61996a7dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BASE:'])[1]/preceding::legend[1]</value>
      <webElementGuid>18799135-2ff2-4799-8fa2-04ef2a0c409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[1]/preceding::legend[1]</value>
      <webElementGuid>c05f1dde-5026-49f4-8658-f04176d1debd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Montos']/parent::*</value>
      <webElementGuid>9897cb14-cd41-4a8b-8926-4f9fc470a776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/legend</value>
      <webElementGuid>d6bc5a3c-e8e8-46f1-8a29-58d5374bd980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = 'Montos' or . = 'Montos')]</value>
      <webElementGuid>4c657aed-9ea0-48cc-8bef-3cf7c17c995f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
