<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monto_base</name>
   <tag></tag>
   <elementGuidId>ae5d07f6-c5c2-41e0-9b1c-733efab40d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='frmConsultaEnvio:panelEnvio:base']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c99dfad0-24b2-45ee-bd37-80acb9e61a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConsultaEnvio:panelEnvio:base</value>
      <webElementGuid>9a457a37-d7a9-42f7-94da-dc9df2a3b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6,19</value>
      <webElementGuid>ff6e2551-24d6-4a25-ae6e-a6a30cf2be43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConsultaEnvio:panelEnvio:base&quot;)</value>
      <webElementGuid>c9332a97-2de4-497f-9856-a6aa53273b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Page_Principal - Olva Courier/iframe_Consulta Envio_iframeConsultaEnvio</value>
      <webElementGuid>f4973fb4-c993-4a3f-b9ef-1a48f60859fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='frmConsultaEnvio:panelEnvio:base']</value>
      <webElementGuid>4851dc0b-f69c-458a-b302-9ee8504474a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='frmConsultaEnvio:panelEnvio:j_idt385']/div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>5131e990-8d35-4869-8b02-142de3a81ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[1]/following::span[1]</value>
      <webElementGuid>456ad2ae-ae75-4e14-b5fa-c6f591c11d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BASE:'])[1]/following::span[2]</value>
      <webElementGuid>16ae6598-b8cc-4f8a-a99b-10bc92648bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCESO:'])[1]/preceding::span[1]</value>
      <webElementGuid>634a6902-2e85-454d-ad63-dc4fc62df64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/.'])[2]/preceding::span[1]</value>
      <webElementGuid>5e120a1e-726b-4095-bf66-36dbade83137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6,19']/parent::*</value>
      <webElementGuid>5aa5280f-affc-4d1a-a924-e20cadf86053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>1ca192a0-c67d-4973-9f12-fc48173183e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'frmConsultaEnvio:panelEnvio:base' and (text() = '6,19' or . = '6,19')]</value>
      <webElementGuid>2a31c89c-dada-4c20-99ae-3a576f973d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
