<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 2Kg (1)</name>
   <tag></tag>
   <elementGuidId>176bdcec-a765-4ee9-8a28-81f809551b20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3741065-25da-460c-9e78-1405309732ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow ml-10 mr-10</value>
      <webElementGuid>3433e755-ed47-4a8d-8a88-b2c316ee40fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_2</value>
      <webElementGuid>f8fdf38a-c007-4698-836d-42b473164cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 2Kg</value>
      <webElementGuid>ad480432-cb88-46d5-b934-999fe0eb6a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_2&quot;)</value>
      <webElementGuid>2ca0d0d0-48f7-4b4b-971b-e15c7fe65315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_2']</value>
      <webElementGuid>a55dadb9-ab0d-4fdc-8c72-57062c8f4ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[3]</value>
      <webElementGuid>c7b7e50b-9cfb-4d5a-8af2-44ceb5cc89dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::div[5]</value>
      <webElementGuid>b8fc0d8e-9932-4e50-9641-fcba79ab51e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>9faf87a7-bdb3-4630-b5b8-12c491864e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_2' and (text() = 'Hasta 2Kg' or . = 'Hasta 2Kg')]</value>
      <webElementGuid>d0066e46-dda5-417f-82ca-43a39e5f4c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
