<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_articulo (2)</name>
   <tag></tag>
   <elementGuidId>5b474c55-2ef9-4f42-9824-b97196624b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_articulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_articulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd3282c3-3753-4be6-9b3f-55d691e94d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed0e414d-41fe-4906-a0ed-09f80c1d8eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51f3cea1-a79e-4f89-82b3-8bdf102b5ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f10bc86a-ee56-4355-8a8d-a02b8932948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especificar artículo</value>
      <webElementGuid>e6afcaa0-dfcc-4370-932a-11c7d7744dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>b2f9846d-0930-4ba1-b2ef-2875bc389461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>31efd689-115f-4076-9882-21465f6610ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>26294967-d457-405c-b2cc-176a421aa024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_articulo&quot;)</value>
      <webElementGuid>1f3cd177-88e3-4940-9a65-0107dc150c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_articulo']</value>
      <webElementGuid>41964968-97ff-44c1-abca-cac07e7f9704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo_descripcion']/input</value>
      <webElementGuid>6be948f8-735a-46df-b428-6959a26eb917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/input</value>
      <webElementGuid>19ba2ab7-c633-4b2f-81cd-283bdf3914e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Especificar artículo' and @id = 'txt_paquete_articulo' and @name = 'txt_paquete_articulo']</value>
      <webElementGuid>eff78a4a-f3fb-49c0-adab-bfaea7d3ad2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
