<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_articulo (1)</name>
   <tag></tag>
   <elementGuidId>f887de81-7cd1-494c-ab97-00a80f5d456e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_articulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_articulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d793ec6-6fa1-4a4d-82b6-5e12c1b764b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>39170125-931b-4354-bca9-8988af81c95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97c8b223-51b9-4036-9b26-a3241b1ca703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>be39e0df-c7d0-44d9-972a-ffbfd5564e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especificar artículo</value>
      <webElementGuid>45842450-472c-49df-a609-d6cc539eab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>117aa9cf-4a24-4b59-98c9-5beef87c81e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>ae6f7bff-a4ea-4cb4-b87d-7c3d0cbe8115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>0f7e1680-ac73-4a5f-812b-369869e34faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_articulo&quot;)</value>
      <webElementGuid>3c017e3a-e673-48fa-95a3-9681c99349c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_articulo']</value>
      <webElementGuid>25375f88-fb94-434d-a0f1-2db2d1f4d824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo_descripcion']/input</value>
      <webElementGuid>2d5d29ae-704e-4deb-a2a1-aeb6c8050aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/input</value>
      <webElementGuid>4daeb435-3f78-4460-a517-8637b10dc015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Especificar artículo' and @id = 'txt_paquete_articulo' and @name = 'txt_paquete_articulo']</value>
      <webElementGuid>29b33074-8cc4-4d3d-933c-cc041b568bdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
