<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT_txt_consignado_dni (2)</name>
   <tag></tag>
   <elementGuidId>c0990454-ff26-4452-80a6-7dab0bbdf497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_dni']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_dni</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aaf2411-8a68-4e1c-9092-b8f62dcb1e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4616fdd0-72f6-4cfb-8666-870040851b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d63e94f-779b-4fc7-a782-3539af038c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>80a1aa8e-cec0-47ef-812c-163a22ee4954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI/RUC/CE</value>
      <webElementGuid>671bcf84-d1c0-462a-84cc-ae263cd29541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-last-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>03424d7b-9602-4a69-b1f4-f4a0b2302cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>373cd50e-df8e-4e9a-a514-966318e25fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>389b4799-17b9-4b8a-88cb-741bbae6357d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>75d8cccb-43fa-4dca-add9-db971c3a4c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_dni&quot;)</value>
      <webElementGuid>8fd60556-f26c-4264-bd92-e4eb54571bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_dni']</value>
      <webElementGuid>36750a7f-8f0b-4e37-bccf-bb2c00a46d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[2]/div[3]/input</value>
      <webElementGuid>780d8479-4f60-40b3-858d-573d48d9081b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/input</value>
      <webElementGuid>5d6db6ac-8ec6-4b2c-a943-683ea7876e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_dni' and @placeholder = 'DNI/RUC/CE' and @id = 'txt_consignado_dni' and @title = '.']</value>
      <webElementGuid>007a92d8-537e-4ecf-9951-b1d82b722399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
