<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT_txt_consignado_dni</name>
   <tag></tag>
   <elementGuidId>dacc19b5-5587-41d6-83df-81c81c6a9601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_dni']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_dni</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2066260-2fe7-47d5-aa02-76ccf2fc973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>67145af4-a626-472b-9360-5513f96c98be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5f836c8-edd1-4a88-b4f1-d0ccfe0949ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>8a370ec7-391b-4ed0-ad46-50519dc6b048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI/RUC/CE</value>
      <webElementGuid>dea210f8-366c-4216-a171-4ea859d4d7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-last-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>9ce79f37-809d-42ee-9316-e3288f896182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f902e065-9b79-48db-abfd-2863ba02799e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>16e3a13f-4fd2-450f-a268-b5deb46e5a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>8b05e14a-3c0c-422d-8d22-d5615a55396b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_dni&quot;)</value>
      <webElementGuid>4c38e6d5-2f51-43e5-a07d-b831a7cdc067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_dni']</value>
      <webElementGuid>4f9adc03-01f8-471e-a627-974e1dd79150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[2]/div[3]/input</value>
      <webElementGuid>a8eef94c-a42f-4811-ab68-bd078da92317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/input</value>
      <webElementGuid>e9d38d2d-5c78-419c-854c-a1beed157298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_dni' and @placeholder = 'DNI/RUC/CE' and @id = 'txt_consignado_dni' and @title = '.']</value>
      <webElementGuid>82d89f57-6d26-4ab3-9de0-67cd67e937c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
