<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 2Kg (1)</name>
   <tag></tag>
   <elementGuidId>7b99e867-51ad-4ec0-bc23-53e5ab78a27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d088905-09eb-48f3-a538-110f634722eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow ml-10 mr-10</value>
      <webElementGuid>d2af4d56-a7ae-4e4c-81ce-ebf92994bf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_2</value>
      <webElementGuid>60b93fdb-af06-476d-a8bf-fc4d72476fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 2Kg</value>
      <webElementGuid>5bb304f7-a02d-4aaa-afff-f0c979c602ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_2&quot;)</value>
      <webElementGuid>742b487a-aac2-47e0-b15f-8c15d1f5260f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_2']</value>
      <webElementGuid>20392bd8-106b-4c4d-9a24-1bd4c0b78e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[3]</value>
      <webElementGuid>4abbb354-a766-4ef7-a84e-614a68b8f93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::div[5]</value>
      <webElementGuid>db08db7a-6286-48d2-9e04-1a8e828bb464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>2f7bfd27-11c6-4414-9c8d-ca1f564622ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_2' and (text() = 'Hasta 2Kg' or . = 'Hasta 2Kg')]</value>
      <webElementGuid>c7eba9ea-6e3c-4db7-948e-f78e313d90c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
