<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iniciar sesin</name>
   <tag></tag>
   <elementGuidId>743aa15c-b6d0-4008-955c-e8827e1dcd90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.sc-AykKC.jTcinx.MuiButton-containedPrimary.MuiButton-disableElevation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e641961-5808-49b0-b2ec-440a52550866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained sc-AykKC jTcinx MuiButton-containedPrimary MuiButton-disableElevation</value>
      <webElementGuid>5917ba24-6562-40e4-8cec-545ef90ca545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd34d9ac-a8d2-4f84-811c-8ff95ea05f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c31cbec-ad00-440c-85e9-e378d60d433f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>45px</value>
      <webElementGuid>b09ead20-fcba-404c-b16a-66df620786c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>177px</value>
      <webElementGuid>7b9294c1-1a37-4d0c-9986-9e34adde4fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar sesión</value>
      <webElementGuid>6b0076dc-7358-4364-82da-55270a835b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root sc-fzXfPe cycdFq MuiGrid-container&quot;]/div[@class=&quot;sc-fzXfPf cykAjz&quot;]/div[@class=&quot;sc-AykKG igIBAL&quot;]/div[@class=&quot;sc-AykKG sc-fzXfOX eClRPq&quot;]/div[@class=&quot;sc-AykKG HtSVF&quot;]/div[@class=&quot;sc-AykKG sc-fzXfOY hJpCqb&quot;]/div[@class=&quot;sc-AykKG gHetfY&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained sc-AykKC jTcinx MuiButton-containedPrimary MuiButton-disableElevation&quot;]</value>
      <webElementGuid>3ee49cdf-1d73-408b-9303-1bc64dbe6e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>3f8bf1c9-27d8-4dbb-9820-6951e408b5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[5]/button</value>
      <webElementGuid>64571cf0-b124-45cb-8344-dd0dc85968f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/following::button[1]</value>
      <webElementGuid>4551247e-0795-4c28-a01e-3e32b0c17ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar'])[1]/following::button[2]</value>
      <webElementGuid>f9533911-c4ab-46c4-acb3-a6292c806506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>9682e413-b820-4b93-a669-68c9793b11e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Iniciar sesión' or . = 'Iniciar sesión')]</value>
      <webElementGuid>0b6e6bd9-e067-48af-a048-0fa2a9b4e783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
