<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresar_MuiInputBase-input MuiInput-input</name>
   <tag></tag>
   <elementGuidId>8afab5f0-3283-47bb-becb-d830c2841729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.MuiInputBase-input.MuiInput-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04239ac4-ba41-44dc-8c4e-a84c0b69967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1efdb17-64b3-471c-8f71-876b250232d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Correo electrónico*</value>
      <webElementGuid>403802cf-385d-435d-b23f-716f7a0eae8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d0df18a-2c3d-4e2c-a444-80aa61b45c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input</value>
      <webElementGuid>5a508d98-8f74-4be4-b608-bb092a2d7f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root sc-fzXfPe cycdFq MuiGrid-container&quot;]/div[@class=&quot;sc-fzXfPf cykAjz&quot;]/div[@class=&quot;sc-AykKG igIBAL&quot;]/div[@class=&quot;sc-AykKG sc-fzXfOX eClRPq&quot;]/div[@class=&quot;sc-AykKG HtSVF&quot;]/div[@class=&quot;sc-AykKG sc-fzXfOY hJpCqb&quot;]/div[@class=&quot;sc-fzXfMC dBFfZG&quot;]/div[@class=&quot;sc-AykKG cIyySi&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root sc-AykKI kzVvE MuiFormControl-fullWidth&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-fullWidth MuiInput-fullWidth Mui-focused Mui-focused MuiInputBase-formControl MuiInput-formControl&quot;]/input[@class=&quot;MuiInputBase-input MuiInput-input&quot;]</value>
      <webElementGuid>afad477f-403d-4944-b9c9-0230820df63c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>328b252d-6ddf-4bd8-b3d4-f424c8801232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>21dfe25d-5602-4956-aefd-b1d22af72b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0c6a4528-9252-46aa-8482-10153034058f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Correo electrónico*' and @type = 'text']</value>
      <webElementGuid>e12c7123-c6c5-4414-bbef-50e9359caa46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
