<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_S.             0.00</name>
   <tag></tag>
   <elementGuidId>0ade5bb2-2829-46b1-99a6-1a81198974ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='1111604']/td[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f06c39c0-c094-4cff-924b-5c09a5eb7bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTableCell-root MuiTableCell-body</value>
      <webElementGuid>d7c9514c-6721-40b4-9c06-7304e24a2c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S/. 
            0.00</value>
      <webElementGuid>2f6b5ead-c39d-4046-a414-6be71c36747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1111604&quot;)/td[@class=&quot;MuiTableCell-root MuiTableCell-body&quot;]</value>
      <webElementGuid>eea4c440-1802-44bb-ba5c-fcde194e8154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1111604']/td[10]</value>
      <webElementGuid>c7af4aa2-3615-45ab-ae24-97427af8569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREDERICH ENMANUEL ADAMES NAVAS'])[1]/following::td[1]</value>
      <webElementGuid>604a6c5b-38e1-479e-a5dd-753cdc63a8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]</value>
      <webElementGuid>1e590ef2-c323-4e12-8d8b-324474a6e8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'S/. 
            0.00' or . = 'S/. 
            0.00')]</value>
      <webElementGuid>2feccea6-f041-494d-be4d-054ad508e80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
