<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_---</name>
   <tag></tag>
   <elementGuidId>b20a33ac-8e33-4cc9-970a-39d7404ba351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='blueTable']/tbody/tr/th[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.odd > th:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b4dda5ec-31e4-4ba7-96e2-b105d629d4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---</value>
      <webElementGuid>22a207f4-a9b4-4d2b-85e3-865e11ebbd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueTable_wrapper&quot;)/table[@id=&quot;blueTable&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/th[6]</value>
      <webElementGuid>fc540bd2-b53d-4ad5-95d9-9149d39070bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr/th[6]</value>
      <webElementGuid>448ee1c9-3755-4a3a-9687-82039042b29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='amazonas - bagua - copallin'])[1]/following::th[1]</value>
      <webElementGuid>e8c1e083-2985-47c1-92f9-3fa0923dad72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lima'])[1]/following::th[2]</value>
      <webElementGuid>83d929b6-0bbd-4b85-8b28-a3c8962593b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 0.00'])[1]/preceding::th[1]</value>
      <webElementGuid>2dae1532-cff9-4b54-b8f1-7bbcfada89dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 18.60'])[1]/preceding::th[2]</value>
      <webElementGuid>2ab34d07-ab07-48ba-b59a-de567c5a90d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='---']/parent::*</value>
      <webElementGuid>7506f65f-cc77-4aa1-92dc-0cb196cbc36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th[6]</value>
      <webElementGuid>69eb43f3-a266-4ef8-891b-6667c1e4428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '---' or . = '---')]</value>
      <webElementGuid>71c9027e-2554-40b9-b15f-cd7fadf2946c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
