<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Editar</name>
   <tag></tag>
   <elementGuidId>9948064a-deca-4149-9e0c-a6a7d59f3534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='parentNode.submit();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.button.icon-action-envio.edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>368717c8-9037-48d6-8780-177010532b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button icon-action-envio edit</value>
      <webElementGuid>8d508b01-0961-4442-a38e-184b71e6cfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parentNode.submit();</value>
      <webElementGuid>1524eaa7-a0fc-49a3-a327-5ecad5676143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>0e4f80bd-3efc-49b6-9a61-ba91e48d457a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueTable_wrapper&quot;)/table[@id=&quot;blueTable&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/form[@class=&quot;btn-edit-acciones&quot;]/button[@class=&quot;btn button icon-action-envio edit&quot;]</value>
      <webElementGuid>c7c35564-a884-43ac-960c-71187037a6f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='parentNode.submit();']</value>
      <webElementGuid>7aa1f2a9-44a8-403a-bdd0-32b4763fc857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr/td/form/button</value>
      <webElementGuid>446f3a9d-0194-43f4-9bb6-866864912beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 16.38'])[1]/following::button[1]</value>
      <webElementGuid>769190c4-4d5c-4b73-a573-1aa073608692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 0.00'])[1]/following::button[1]</value>
      <webElementGuid>03a59e3a-b7d5-4ba8-990a-be055a4462e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/preceding::button[1]</value>
      <webElementGuid>d55678a3-2bef-41e0-b9c9-d5e7913310fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/preceding::button[2]</value>
      <webElementGuid>b41efdf3-8f60-4268-b485-deae3d34d49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar']/parent::*</value>
      <webElementGuid>3cac5306-e033-4503-aef6-12cb905acf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>755287f3-f9fd-49ba-9d3f-919203957b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>58c6eb6c-580e-4cfc-89f1-d0cb5878e599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
