<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S 1800.00_chk_regulacion</name>
   <tag></tag>
   <elementGuidId>c02cf386-41f4-4cef-9aac-15451bc01c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_regulacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chk_regulacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6df6ffd6-9f5a-4e3c-8710-c5cab955c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_regulacion</value>
      <webElementGuid>c1cff148-c46f-466a-912f-e28c510a0057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radiobtn</value>
      <webElementGuid>ace99f64-c030-446e-965b-6c17911887c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk_regulacion</value>
      <webElementGuid>740bb8a6-5aa4-4436-90ac-0314dc84c4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>538a8d33-d6cc-462e-860f-e9fa0609cdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8a4050fd-e7cb-41cb-a04b-df0cc03d9855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>f9226878-c7bb-475a-8b95-737153c6cd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_regulacion&quot;)</value>
      <webElementGuid>343a50d2-2210-4146-9823-f4b39ae71fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_regulacion']</value>
      <webElementGuid>602445e8-7040-4327-a21e-3b73b8c4eee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='op_regulacion']/ul/input</value>
      <webElementGuid>a18ee7e8-97e4-4e9e-a1f1-9753783b662a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input</value>
      <webElementGuid>2296aadd-f405-44fd-8e41-6b18a4202be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'chk_regulacion' and @name = 'chk_regulacion' and @type = 'checkbox' and @title = '.']</value>
      <webElementGuid>8952049c-e41b-4bf3-9889-3eee5000645e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
