<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 1Kg</name>
   <tag></tag>
   <elementGuidId>b1683dfb-d467-425d-81cc-b2949b4b5268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7d7d5bb-479d-4376-9819-4cf38d91c45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow mr-10</value>
      <webElementGuid>ff17f543-6300-4605-913e-6269b226a83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_1</value>
      <webElementGuid>5d86b062-009c-4694-83fb-cfea4e33fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 1Kg</value>
      <webElementGuid>3baa1282-db89-4c1e-9761-fdf3608545c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_1&quot;)</value>
      <webElementGuid>bd129556-1089-47f1-a496-792f70badac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_1']</value>
      <webElementGuid>a2d0ef9a-cf32-4341-9a24-5a46aed8dfcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[2]</value>
      <webElementGuid>10802280-8a3e-4d36-a046-98b8ee8d8462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::div[4]</value>
      <webElementGuid>7d1de190-5be2-4197-9ba4-c11ec2892ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILES DE OFICINA'])[2]/following::div[10]</value>
      <webElementGuid>b9648f01-15ee-430a-9642-2ffddde80b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hasta']/parent::*</value>
      <webElementGuid>9e74a803-ec19-472e-8475-6883ad99a627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>14bd51f9-fc8f-41b2-8fe6-22d0126304b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_1' and (text() = 'Hasta 1Kg' or . = 'Hasta 1Kg')]</value>
      <webElementGuid>60fabd62-6761-4793-9084-7bfa8e18ee14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
