<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT_txt_consignado_dni</name>
   <tag></tag>
   <elementGuidId>e6eda9e5-2d88-4244-a3f5-b15e18d22010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_dni']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_dni</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb3e969-f7da-459b-ba31-06349ff03bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a868550-4933-4b77-97eb-0ac5203ae878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4da6dcd-9a39-48b2-9fc6-5cb791c9e375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>22adcddc-11d8-4f90-be0d-dee1cd57d97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI/RUC/CE</value>
      <webElementGuid>2d796b80-fb49-49ed-ace9-88563cfe22ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-last-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>6c6715fc-7a6c-4452-85de-3ebedacc30ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a60da42c-2cd0-4260-8db0-b1f74242767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>cb2e708d-ba52-42ce-99bd-848016368c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>d47dfe87-8498-400d-a86e-c0da2645c505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_dni&quot;)</value>
      <webElementGuid>3cfec184-5431-4bbc-a501-5158522948cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_dni']</value>
      <webElementGuid>6a443b2e-c2a0-41d0-a9da-70f080ec78c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[2]/div[3]/input</value>
      <webElementGuid>c9028da5-6ac7-4b56-bb47-8c132e31f1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/input</value>
      <webElementGuid>f610821a-427e-4389-b342-7236a0a3867a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_dni' and @placeholder = 'DNI/RUC/CE' and @id = 'txt_consignado_dni' and @title = '.']</value>
      <webElementGuid>7aa742e2-4580-4070-b993-8ea50cd9f6fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
