<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_OLVA LINCE - AV. ARENALES 1775</name>
   <tag></tag>
   <elementGuidId>9b39818d-e59c-48e7-bb2a-c99efd0a70b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmComprobante:oficina_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>02534cf1-2279-409b-8f94-02f7466b9c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>2c2a0dee-b1b6-4ef9-adc0-200f47b0f5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>f92a8ff2-20a8-4019-a24d-bb328f3249e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>71db9987-7ff4-4d37-9dba-be337837c216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>06792c9d-a40e-4284-adc5-dd1f73140f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmComprobante:oficina_4</value>
      <webElementGuid>1fb8e0fe-936e-4784-be49-d39e087cc1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA LINCE - AV. ARENALES 1775</value>
      <webElementGuid>914e4f09-167c-4d02-9326-4a72ad9aeb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmComprobante:oficina_4&quot;)</value>
      <webElementGuid>c08d6857-ead0-4e7e-a3e6-9d4dfe6daf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>4c118645-4f85-45b1-8b33-9ec305500697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Olva Courier  Datos Personales/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>f84c6ca1-31e9-4e89-aa1b-62734f5f96b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Object Repository/Page_Principal - Olva Courier/Page_Principal - Olva Courier/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>74485bf0-0188-4333-ad4b-cdc28a578577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmComprobante:oficina_4']</value>
      <webElementGuid>3e382e36-3e50-4480-9e7f-521d3d7901e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmComprobante:oficina_items']/li[5]</value>
      <webElementGuid>0686d1ce-c844-4476-aa53-8242e8f16900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EX-M.EDUCACION'])[2]/following::li[1]</value>
      <webElementGuid>7b9c8ff8-eeff-4bad-b6d9-33d2f634391c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PALACIO JUSTICIA'])[2]/following::li[2]</value>
      <webElementGuid>cd7aaf35-ae2c-4e64-94b0-a955ee7bedd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA ALMACEN INTERNO -AV. ARGENTINA 4458 CALLAO'])[3]/preceding::li[1]</value>
      <webElementGuid>38abdb2e-6171-44ce-baef-1549241c015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLVA SAN ISIDRO - AV. ARAMBURU NO. 978'])[2]/preceding::li[2]</value>
      <webElementGuid>0fa5bf4a-f90a-4e21-8f4b-ba167ee59dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/ul/li[5]</value>
      <webElementGuid>a256f7a5-14b7-42fb-ac94-ddd4dbca435a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmComprobante:oficina_4' and (text() = 'OLVA LINCE - AV. ARENALES 1775' or . = 'OLVA LINCE - AV. ARENALES 1775')]</value>
      <webElementGuid>63b57921-6ebd-47b1-a4b9-7b642a570224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
