<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1Kg</name>
   <tag></tag>
   <elementGuidId>1578cabe-da17-4888-b33f-b85799f3d68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_1']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_1 > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>40339f42-f905-4974-9628-90f6ab0851b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Kg</value>
      <webElementGuid>1b9f1b00-ab95-41c7-bf1d-4ebd6c61c426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_1&quot;)/b[1]</value>
      <webElementGuid>f8655a00-7e50-454d-bb63-99b56063f315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_peso_1']/b</value>
      <webElementGuid>c2de839f-95ec-4c8e-9d4f-7ffd8bcbb218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::b[1]</value>
      <webElementGuid>9b9e955f-f0be-47c6-9275-2e044be69784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1Kg']/parent::*</value>
      <webElementGuid>ade02c10-5297-41a3-a3b9-de8090c9bcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/b</value>
      <webElementGuid>2bf7be95-206f-4a78-8483-98b973755ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '1Kg' or . = '1Kg')]</value>
      <webElementGuid>8e5df833-505c-4cfc-b349-8a434a47603e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
