<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_3Kg</name>
   <tag></tag>
   <elementGuidId>996c17ef-538d-49b0-9206-b9c195abdab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_3']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_3 > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>14b9cb8e-32c9-43bd-b6bf-e3604f827fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3Kg</value>
      <webElementGuid>fec0f175-0b43-4278-8557-7982c7b9d214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_3&quot;)/b[1]</value>
      <webElementGuid>db6b7fac-2194-4a24-858e-c44f346dc010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_peso_3']/b</value>
      <webElementGuid>5bf07148-050f-4acd-8101-3931c267aa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3Kg']/parent::*</value>
      <webElementGuid>80d57e72-365f-41ca-8dd7-ce6e51edf69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/b</value>
      <webElementGuid>ad0a969d-db47-4e65-b842-b646bb364f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '3Kg' or . = '3Kg')]</value>
      <webElementGuid>f802f269-2840-4508-93d2-7e399fb311aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
