<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 4Kg</name>
   <tag></tag>
   <elementGuidId>75c8d791-b10b-43ed-ad3f-71c153b78e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7cf0373-a265-4908-a3ff-9ed5107bd810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow ml-10</value>
      <webElementGuid>df053bed-1b07-4d3b-b3c4-dc5b830abf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_4</value>
      <webElementGuid>e6121045-85a2-478c-b105-de4f812ea219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 4Kg</value>
      <webElementGuid>bc9b5b24-1d79-4716-9ca6-4a9ff62de8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_4&quot;)</value>
      <webElementGuid>193d50d9-de9e-4f38-97bd-a15e17bc6d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_4']</value>
      <webElementGuid>e43551c4-3088-4165-a93f-cba7318b3968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[5]</value>
      <webElementGuid>e4e5907f-b5cc-4dd5-bf02-e7ebb6b98da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No encuentro el peso de mi envío'])[1]/preceding::div[4]</value>
      <webElementGuid>ec723c9d-8222-4220-a194-42613cf2b73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[5]</value>
      <webElementGuid>e278d4a4-7779-46cc-b848-b50b9c3d1453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_4' and (text() = 'Hasta 4Kg' or . = 'Hasta 4Kg')]</value>
      <webElementGuid>568dd646-124e-4ec9-b597-13a6bde93e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
