<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 5Kg</name>
   <tag></tag>
   <elementGuidId>2f8552f2-e219-4822-99fc-6c697493c6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f0e53ff-cc8f-4720-a5d7-5d3b1c27be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow mr-10</value>
      <webElementGuid>5d4d403a-e3ca-4a2e-8d09-b488bd09a4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_5</value>
      <webElementGuid>281268b7-3fd6-4835-9677-7865a1e1af2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 5Kg</value>
      <webElementGuid>b9e6c39a-8448-47ec-9e58-817fa98154b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_5&quot;)</value>
      <webElementGuid>5430c4c8-1756-42dd-bac3-e0263a06deaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_5']</value>
      <webElementGuid>5118ff19-63c5-458a-a39b-f7d6344674dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_peso_inferior']/div[2]</value>
      <webElementGuid>114a4008-eb21-4da2-9aaa-05810956e56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No encuentro el peso de mi envío'])[1]/preceding::div[1]</value>
      <webElementGuid>51c139c6-01ef-4091-8d69-c41e002757da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]</value>
      <webElementGuid>c51af74a-c43d-4aa0-a9e2-1da1e721ecf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_5' and (text() = 'Hasta 5Kg' or . = 'Hasta 5Kg')]</value>
      <webElementGuid>e0f251eb-f5ee-4d4f-9f59-e319019eb474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
