<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 1Kg</name>
   <tag></tag>
   <elementGuidId>a7114b08-5264-4b29-8a5f-45dbe3d53fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8096feda-0d2e-4e98-b3f1-d22f6ad26d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 border-yellow mr-10</value>
      <webElementGuid>8bf7347f-6d17-4ab1-8541-f030f7d24f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_1</value>
      <webElementGuid>44dbfcf6-0cc6-4eb9-a837-e3eb5b54db57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 1Kg</value>
      <webElementGuid>2d342249-12c3-4e92-a1b3-1229ef0bced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_1&quot;)</value>
      <webElementGuid>efdadf5d-589c-4354-8831-16582ec26003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_1']</value>
      <webElementGuid>87173c5e-2b10-4800-afdd-c9c6d20f776a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[4]/div/div[2]</value>
      <webElementGuid>670c2b1a-cfad-434f-8bea-b5afa6fee3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso del envío'])[1]/following::div[4]</value>
      <webElementGuid>5e9a78bb-8776-4d14-a429-5d9f634d2ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILES DE OFICINA'])[2]/following::div[10]</value>
      <webElementGuid>4f336b61-2a59-4a0b-b673-c65bea220fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hasta']/parent::*</value>
      <webElementGuid>d22f6847-9ff7-493f-8bb8-723500dc95a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>ec535a9f-a7a7-48fe-841a-883a4ed95064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_1' and (text() = 'Hasta 1Kg' or . = 'Hasta 1Kg')]</value>
      <webElementGuid>06c8cfd8-d3fc-4884-9a1a-477b9522efcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
