<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_valor</name>
   <tag></tag>
   <elementGuidId>ebd7da24-eee3-47da-a38d-07d6b7d54c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_valor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_valor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc37e6de-96db-4972-a5c4-8fdc7e2acc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>adace7ba-3241-45dd-ac63-6fa046e71caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>4eccc618-8d72-4cb3-8e49-4a02a7dcd5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f90c57db-d3bc-4ca4-a808-56b863eda4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>f5f179ff-3494-46b6-a052-b86ab86a94d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);</value>
      <webElementGuid>38178889-a7a9-45cd-a61f-3948a5ac904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1d7e449a-f89a-43c6-ba0b-957f410fbcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_valor</value>
      <webElementGuid>5827ab6f-f30e-44e4-be51-2f509be964a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_valor</value>
      <webElementGuid>85e22908-b604-49f3-a63f-8e6b262e4d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Valor S/</value>
      <webElementGuid>60d21876-630e-4b5e-bf30-5fe4d86b39a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt</value>
      <webElementGuid>683a3425-2e41-4777-b298-9d01197bfadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Colocar el valor real del producto, en caso de siniestro, este será el monto para los cálculos correspondientes.</value>
      <webElementGuid>7d98bc6a-9c63-4524-9d77-8c59efabfbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_valor&quot;)</value>
      <webElementGuid>acc4f6c8-9d37-4fe1-8fe3-66b6570982ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_valor']</value>
      <webElementGuid>6b3f3f37-83cb-4eff-98b8-f1891f4a3740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias']/div[2]/div[4]/input</value>
      <webElementGuid>81cd316a-8deb-4aa8-9880-1456508f0e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[4]/input</value>
      <webElementGuid>d53daae6-c110-4ae1-9695-42464fd5186e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'txt_paquete_valor' and @id = 'txt_paquete_valor' and @placeholder = 'Valor S/']</value>
      <webElementGuid>3918799f-06c8-4b84-ac6c-d356e524a481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
