<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR</name>
   <tag></tag>
   <elementGuidId>60604a84-f093-4772-8ac4-639b058e1ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_aceptar_tipo_envio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_aceptar_tipo_envio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4947a5a9-ccb6-4178-b800-73b3544feb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_aceptar_tipo_envio</value>
      <webElementGuid>9226d0f4-2ab1-49f5-9a81-fd99e753efc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f0241a6-6488-4ff8-8e43-f6b0d8f312f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>f32ad8dc-b1bb-40a6-8c13-31ec6a6844d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>e4b5167f-3dff-4563-8ccf-8bdf04622bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_aceptar_tipo_envio&quot;)</value>
      <webElementGuid>0a772f75-0a08-4dad-acbf-05692b0e169f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_aceptar_tipo_envio']</value>
      <webElementGuid>62f5beab-a086-46c8-be52-9dc5a1b754eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/button</value>
      <webElementGuid>61275304-df0e-490b-8538-5fa4363d9f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS DE TARJETAS, AGENDAS Y CAJAS NAVIDEÑAS'])[1]/preceding::button[2]</value>
      <webElementGuid>9f2e2b36-5b73-4aef-8c81-28636b02fe6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUAR']/parent::*</value>
      <webElementGuid>9c402f15-0b4e-45f8-b3d8-fb437abcfad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e26022a2-ca1d-4edc-bc11-033ce3a2255d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_aceptar_tipo_envio' and @type = 'button' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>94aa10eb-4b90-4ee0-88fc-b40e3f461431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
