<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAGAR (1)</name>
   <tag></tag>
   <elementGuidId>cefc68d6-fe8b-4a95-9d45-9d45647d88d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-tottem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-tottem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d1aabe6-bfae-4480-a5c3-b9e3a6d54583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-tottem</value>
      <webElementGuid>ce1ce3be-5c80-442d-9da5-133c3a7cbef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-pagar btn-pagar-2</value>
      <webElementGuid>3a7a468b-05c0-4d4e-922c-ab6934c4e5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PagarJS.activarPOS()</value>
      <webElementGuid>21da590e-628e-4d32-9373-7f4a569de8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGAR</value>
      <webElementGuid>a1a8e2f6-f071-4b4d-b050-5bdabff2aabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-tottem&quot;)</value>
      <webElementGuid>c3a71a5b-537a-447b-8bba-e160beac143b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-tottem']</value>
      <webElementGuid>d3b8a541-28e1-4776-8d99-265fb11d4b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagarTottem']/button</value>
      <webElementGuid>5489b913-a704-4cf2-a3e8-70c78bb7e232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/following::button[1]</value>
      <webElementGuid>265dcde4-58c9-4c01-b0ba-4defefa6a870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 76.41'])[1]/following::button[2]</value>
      <webElementGuid>e7902c25-a7ab-42bd-932e-81f4d78dfb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[2]/preceding::button[1]</value>
      <webElementGuid>6251706f-970c-4125-a546-86cd841dd813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[3]/preceding::button[3]</value>
      <webElementGuid>a93c6b84-d4a0-4931-b4ed-592a9fd34160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAGAR']/parent::*</value>
      <webElementGuid>25a96e3e-44cf-4c31-9078-87aeef3b158b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div[2]/button</value>
      <webElementGuid>cd8e2afa-29ac-4f18-9464-acd0dd2f1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-tottem' and (text() = 'PAGAR' or . = 'PAGAR')]</value>
      <webElementGuid>2420a9f9-a155-42f9-8bf5-a455b6208064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
