<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAGAR</name>
   <tag></tag>
   <elementGuidId>91824bca-1d43-4d90-8780-8d8015805683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-tottem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btn-pagar-tottem-empaque&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74b33f2f-8b50-49af-8efd-f5b18e6325b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-tottem</value>
      <webElementGuid>25d45785-fe47-4651-8c37-edda94893e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-pagar btn-pagar-2</value>
      <webElementGuid>d410cf20-121f-4280-aa91-6bcd7b57b1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PagarJS.activarPOS()</value>
      <webElementGuid>a7d7d565-1368-4b68-975f-d5afda542226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGAR</value>
      <webElementGuid>ce57ee42-e1af-4c07-9909-9ac22bd7cd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-tottem&quot;)</value>
      <webElementGuid>676e96af-044b-463b-8bf7-14f816da4578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-tottem']</value>
      <webElementGuid>496386e9-968c-4e41-bf4f-87521f7a7d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagarTottem']/button</value>
      <webElementGuid>49a3cf25-0c44-442b-b5e8-5c4f3547534b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/following::button[1]</value>
      <webElementGuid>a2b556f5-4426-4f83-95e4-278d94fda6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 14.50'])[1]/following::button[2]</value>
      <webElementGuid>13a82fee-0c0b-481e-971b-918e0a95e2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[2]/preceding::button[1]</value>
      <webElementGuid>65d5ea85-91de-48b8-86a9-d6eca7d2fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[3]/preceding::button[3]</value>
      <webElementGuid>cfde5496-7094-4ace-ab3a-46761c9defe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAGAR']/parent::*</value>
      <webElementGuid>52b193d0-5f5b-4418-b77e-1909b60603c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div[2]/button</value>
      <webElementGuid>5a820ba8-425a-4d23-9f87-f71931119a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-tottem' and (text() = 'PAGAR' or . = 'PAGAR')]</value>
      <webElementGuid>5ed12505-5847-4bee-9249-3848d2ba91d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
