<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_S</name>
   <tag></tag>
   <elementGuidId>72f762d9-594e-44e9-a74c-ecbb9c9ee5a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='txt_total']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_total</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5c08e166-3180-4a8e-861f-8a96da1395b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>91215838-aba6-4c73-90b2-e3a354c7b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>1f0536f5-2869-41d4-bac6-6d86c9424c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_total</value>
      <webElementGuid>7ff40408-24ac-4443-b21c-381e90633ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S/ 14.50</value>
      <webElementGuid>f9e08688-ba6d-4443-a99f-3174f02c9405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_total&quot;)</value>
      <webElementGuid>90fdbc4b-bd20-419c-afca-e5ad41e8659b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='txt_total']</value>
      <webElementGuid>af287864-a052-48f0-b40a-7e2e44ebe63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso3']/div[2]/div[3]/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>af5668f4-caf9-468b-850f-8ef5d0c02377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::td[1]</value>
      <webElementGuid>6cceab51-b1a7-41a0-9448-15d933fbb439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 2.21'])[1]/following::td[2]</value>
      <webElementGuid>04eedfe1-48ed-4b54-bb6b-d24054e4be6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/preceding::td[1]</value>
      <webElementGuid>2d1d6f5b-afc1-45f0-a5f4-550cd5f45568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[1]/preceding::td[1]</value>
      <webElementGuid>4f3f8eeb-96cf-4f65-bea9-f5b6dece3872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S/ 14.50']/parent::*</value>
      <webElementGuid>58acb001-83aa-409e-b1ac-5a9fe07ca524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>c2bff660-81a0-4b8b-aef1-a01862f7c5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'txt_total' and @name = 'txt_total' and (text() = 'S/ 14.50' or . = 'S/ 14.50')]</value>
      <webElementGuid>43ca2509-e428-4340-ab84-b5a4db6947d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
