<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar</name>
   <tag></tag>
   <elementGuidId>596a2254-7f33-4a2e-910c-f37c34fe3485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonAceptarClave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonAceptarClave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>509599c7-6d05-4512-896c-5fd6df4ca175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-footer button-enabled</value>
      <webElementGuid>ab4b7dbd-f655-4c0b-a52c-a65e7e83c325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonAceptarClave</value>
      <webElementGuid>535fd1a4-d977-4576-9c83-e589524ed84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Aceptar
                </value>
      <webElementGuid>7364043f-8439-4f62-a82c-d8d8fe3cdfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonAceptarClave&quot;)</value>
      <webElementGuid>10ad8ea8-6249-4465-b98a-cc3d0bc03281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonAceptarClave']</value>
      <webElementGuid>15fd4fd6-15ee-4d5b-9f2f-8c2e8a8ae98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalClaveSeguridad']/div/div/form/div[2]</value>
      <webElementGuid>db6cb8c9-2b9f-4f40-8352-b1b39db0baec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envía la clave de seguridad a la persona que vaa recoger el envío.'])[1]/following::div[1]</value>
      <webElementGuid>096c07ae-b27b-4bb1-9add-b0326cfbafaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡IMPORTANTE!'])[1]/following::div[1]</value>
      <webElementGuid>ff9b7c97-cede-4b1a-b478-8e2b36ad6d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/preceding::div[1]</value>
      <webElementGuid>9ea7d4ca-8de1-4148-9f0f-adb4ac0449d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/form/div[2]</value>
      <webElementGuid>e42116a4-03b9-4d09-aabd-c23ee5a776ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonAceptarClave' and (text() = '
                    Aceptar
                ' or . = '
                    Aceptar
                ')]</value>
      <webElementGuid>2902c782-5656-4a81-96da-a9705a02d9d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
