<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar (1)</name>
   <tag></tag>
   <elementGuidId>1557199d-04bc-4b5b-aae8-4bd799926c18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonAceptarClave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonAceptarClave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a8d4786-5346-4a25-bde4-906fbfab78ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-footer button-enabled</value>
      <webElementGuid>464ad30a-00c1-43b1-ae51-3580cc47fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonAceptarClave</value>
      <webElementGuid>9c1a1387-9191-4430-b149-862c602aec8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Aceptar
                </value>
      <webElementGuid>e6c0b169-ccd0-463e-83f0-02ae047b8ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonAceptarClave&quot;)</value>
      <webElementGuid>32852dcf-231d-4b8e-b8e6-a94f9576e5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonAceptarClave']</value>
      <webElementGuid>f663a6ce-2362-4abb-9731-3d4c9c8fa8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalClaveSeguridad']/div/div/form/div[2]</value>
      <webElementGuid>8c60b191-79b9-48ea-8357-0fe5c13bdb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envía la clave de seguridad a la persona que vaa recoger el envío.'])[1]/following::div[1]</value>
      <webElementGuid>d6c2c869-e14c-498e-84ba-d9abea7f94ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡IMPORTANTE!'])[1]/following::div[1]</value>
      <webElementGuid>209bf58c-f0b4-4593-812d-c839f54cee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/preceding::div[1]</value>
      <webElementGuid>5aacb581-488f-43f4-b478-4d5ae2ab05c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/form/div[2]</value>
      <webElementGuid>fc417ea4-1512-41e3-b2f1-0687dd4d5120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonAceptarClave' and (text() = '
                    Aceptar
                ' or . = '
                    Aceptar
                ')]</value>
      <webElementGuid>8294127f-5fd4-48b6-a5cb-8d8d50d0260b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
