<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tienes envos con recojo en tienda, se_8615a0</name>
   <tag></tag>
   <elementGuidId>45cdee8d-7372-4f33-aa38-c4ec2e079b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digito4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#digito4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab7eed0d-a6cd-4c7e-9f1b-acb78aa29187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digito4</value>
      <webElementGuid>8b34d404-c305-48a1-8e27-35f85bb2b365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f5ab6cca-d72b-49e0-bb72-97a7df15bbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>2b3ae388-66bc-4456-88b7-e317766d6ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fdcd948a-d0bb-44f4-94cc-08e7194c9d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return digitKeyOnly(event)</value>
      <webElementGuid>dc5039f1-6029-4232-8698-e27c2436adbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);</value>
      <webElementGuid>25c25c6a-7ca5-4994-bdd3-7bcff125b574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digito4&quot;)</value>
      <webElementGuid>51e44c49-673c-4c64-ab99-7d6d40c63f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digito4']</value>
      <webElementGuid>f4968731-6fbc-4b80-9cd6-8f63b71180bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalClaveSeguridad']/div/div/form/div/div/div[4]/input</value>
      <webElementGuid>90fd4d8a-5fc8-451b-bf3f-6edc04b55bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/form/div/div/div[4]/input</value>
      <webElementGuid>37786984-59ad-4d21-bf75-a1ea340a5982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'digito4' and @type = 'number']</value>
      <webElementGuid>2e2347c6-36ce-44fb-ab37-6e78ae82e7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
