<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eliminar</name>
   <tag></tag>
   <elementGuidId>c7d916cd-d852-4df4-a09b-fca4492ba585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[(text() = 'Eliminar' or . = 'Eliminar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_eliminar_856 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de29622a-fdb2-4101-bcdb-ce6148d2cc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>04b32bbd-19f5-4133-834d-5f5bf8097f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_eliminar_856&quot;)/a[1]</value>
      <webElementGuid>29fb7daa-0e8d-4ae3-8950-27e30b84aa5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_eliminar_856']/a</value>
      <webElementGuid>bfb12f8e-8443-42f6-9485-60213aba9a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eliminar')]</value>
      <webElementGuid>7815e464-bf8f-4bfb-9597-9c79a0aefa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::a[1]</value>
      <webElementGuid>9b530c91-014c-4f7a-9c44-0e2db658eaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>197ed817-113a-42a0-afc8-89b6b78624d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::a[1]</value>
      <webElementGuid>170e3942-ace0-427a-b183-ed062c427a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/'])[3]/preceding::a[1]</value>
      <webElementGuid>47e51269-fd72-4118-a37c-148f18b75d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminar']/parent::*</value>
      <webElementGuid>ac8d6a12-eeed-4775-9a40-767946b1d09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/button/a</value>
      <webElementGuid>1cf45128-c792-4834-b242-c35a04fe9882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>c6cd897c-ed3d-4428-99c1-77bae8dee357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
