<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Si</name>
   <tag></tag>
   <elementGuidId>59680461-75ba-437d-b821-5242e4643d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='bottom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-warning.mt-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd0c84af-2ec7-4ce5-b24b-5708ddd0d5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>d6768bec-4748-4eed-a868-0548b577a9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mt-10</value>
      <webElementGuid>97dd3b99-7116-48fe-a38c-f947ef360dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Si</value>
      <webElementGuid>de5e4564-ce44-4d1e-9c01-6733df0a6f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alerta-domicilio&quot;)/div[1]/div[4]/button[@class=&quot;btn btn-warning mt-10&quot;]</value>
      <webElementGuid>57daf269-9dc3-46d0-803c-5089ee2e676f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='bottom']</value>
      <webElementGuid>eed845b7-d52f-4c45-a638-a621584a6639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alerta-domicilio']/div/div[4]/button</value>
      <webElementGuid>115ac9d6-e2a3-48de-908e-d940658a38af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Desea agregar más cajas a su compra?'])[1]/following::button[1]</value>
      <webElementGuid>07e05ef5-cc50-4fc3-a567-bd8309750565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad de cajas inválida'])[1]/following::button[1]</value>
      <webElementGuid>95578fe4-645a-4508-81df-0af4b58c18a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>5ba0ec20-fc83-4fdc-a2d4-b5c31dd12dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a8835972-7e8b-49cd-99c4-e81b25a19675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'bottom' and (text() = 'Si' or . = 'Si')]</value>
      <webElementGuid>4af7086f-3912-490b-94fb-3f333493bcba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
