<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe seleccionar un distrito destino pa_39940b</name>
   <tag></tag>
   <elementGuidId>a65c670e-a9bf-42fe-8baf-9634c7e0bd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_descripcion_ubigeo_caja_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_descripcion_ubigeo_caja_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d8efa08-8f2f-49cf-9676-5426d27e4abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_descripcion_ubigeo_caja_msg</value>
      <webElementGuid>1828b4a6-0920-4c6d-9321-1583207e0183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>a37e7fb8-4948-48b0-871e-7d82073027b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe seleccionar un distrito destino para continuar</value>
      <webElementGuid>9a649fd5-675d-42aa-9053-682c3b8180c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_descripcion_ubigeo_caja_msg&quot;)</value>
      <webElementGuid>c75e459f-280d-49b6-bd6d-2ab42c6e8015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_descripcion_ubigeo_caja_msg']</value>
      <webElementGuid>c8182741-12e4-490c-924b-e2f83bdb4691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-ubigeo']/div[2]</value>
      <webElementGuid>d6c02f74-237c-44cd-8c78-f4cab26fc918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PURUS - PURUS'])[4]/following::div[1]</value>
      <webElementGuid>82be4168-44ae-4436-be49-9d0e0ff9c2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PADRE ABAD - NESHUYA'])[2]/following::div[1]</value>
      <webElementGuid>c8bedc61-37e2-4eca-ad8a-3735449756c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La direccion debe ser mayor a 3 caracteres'])[1]/preceding::div[3]</value>
      <webElementGuid>d7a73923-ef13-44f7-a4f0-af7c82aad0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La referencia debe ser mayor a 3 caracteres'])[1]/preceding::div[8]</value>
      <webElementGuid>f7a77bfc-e3ac-4301-ad1b-9cedf2aa2055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe seleccionar un distrito destino para continuar']/parent::*</value>
      <webElementGuid>8aadd783-175b-4a37-a1ce-378056cae822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[2]</value>
      <webElementGuid>977c0d57-fd49-4c41-9e3e-40dc1ec42fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_descripcion_ubigeo_caja_msg' and (text() = 'Debe seleccionar un distrito destino para continuar' or . = 'Debe seleccionar un distrito destino para continuar')]</value>
      <webElementGuid>2e60800f-fc4a-4b57-9743-0e3a0448380f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
