<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar</name>
   <tag></tag>
   <elementGuidId>21b9968b-78d8-4cb5-be73-11fdf1d0febb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonAceptarClave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonAceptarClave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3099b20c-6eea-45de-aeb3-d585f496e3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-footer button-enabled</value>
      <webElementGuid>bf8cf60c-12c5-4734-93b3-606ae7946543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonAceptarClave</value>
      <webElementGuid>74f8114b-b125-44ed-af08-fcfef8180774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Aceptar          
                </value>
      <webElementGuid>e59696ab-6cb3-4308-918d-10bbe4adc6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonAceptarClave&quot;)</value>
      <webElementGuid>4b49a275-d6f7-4411-beaf-ffe4645d1c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonAceptarClave']</value>
      <webElementGuid>cabd1ebe-fcdd-40f8-b478-2a4953a662dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalClaveSeguridadCaja']/div/div/form/div[2]</value>
      <webElementGuid>1198ad93-e482-4a5b-8224-1254f203a207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuerda recoger tus empaques con tu clavede seguridad'])[1]/following::div[1]</value>
      <webElementGuid>92b37ffb-9b48-4a17-94dc-3e30290be886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡IMPORTANTE!'])[1]/following::div[1]</value>
      <webElementGuid>83f49c4a-3599-4756-a5e5-fe8cc4d5df04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[8]/preceding::div[1]</value>
      <webElementGuid>a1c21db6-d908-47c0-9837-a7b0fafda400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>b078568f-9279-4755-a176-6d2226b4b48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonAceptarClave' and (text() = '
                    Aceptar          
                ' or . = '
                    Aceptar          
                ')]</value>
      <webElementGuid>90fe8522-f708-4240-87b1-e81c4833ece9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
