<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El CE debe tener 9 dgitos</name>
   <tag></tag>
   <elementGuidId>b83604a4-43ef-4d8b-bd71-58bca4c69700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_documento_cliente_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33d08355-34d4-4956-9e03-5c1cd21ff692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente_msg</value>
      <webElementGuid>b3352694-c4e4-4297-bd1d-702d2531cd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>94eba004-82ff-4f61-8948-652af7bf9ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El CE debe tener 9 dígitos</value>
      <webElementGuid>6dd7c47f-ea83-4303-8146-5ed161a9168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente_msg&quot;)</value>
      <webElementGuid>65b13008-3323-434d-9b84-d8722803c70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_documento_cliente_msg']</value>
      <webElementGuid>1059b8be-2d2a-4f88-8a83-9417ee8ef148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/div</value>
      <webElementGuid>8f5a41b5-1ff6-4b9f-9b8d-0fc6080d29a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[3]/following::div[3]</value>
      <webElementGuid>d3827118-a29c-40f5-9efc-f75ca5b6522a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[3]</value>
      <webElementGuid>472e6980-ed3d-453b-a82b-9072441c6e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese 9 digitos'])[1]/preceding::div[1]</value>
      <webElementGuid>602efa3c-8510-4522-97dc-05698b464ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola,'])[1]/preceding::div[5]</value>
      <webElementGuid>d8672674-d4ce-43dd-bb13-c0ede02ea559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/div</value>
      <webElementGuid>3be8e1cf-8e1a-434c-824b-cb5e67fbf262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_documento_cliente_msg' and (text() = 'El CE debe tener 9 dígitos' or . = 'El CE debe tener 9 dígitos')]</value>
      <webElementGuid>ffb746f3-ee3a-4a8c-9aec-258e1881705a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
