<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El DNI debe tener 8 dgitos</name>
   <tag></tag>
   <elementGuidId>6562bc87-ceab-45d9-a1ff-33cfbe0af07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_documento_cliente_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24febc18-67d2-4d3f-9d0d-3f8fc16d6050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente_msg</value>
      <webElementGuid>d3e94070-de18-4477-90cf-7944db570d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>9c83c48c-fc74-41dc-9b6d-c82d7e1f2bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El DNI debe tener 8 dígitos</value>
      <webElementGuid>7452fe07-5e50-4f45-9cee-35fbd2760a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente_msg&quot;)</value>
      <webElementGuid>49bfb64e-d0e1-4f3f-b8ed-283f52bdfa97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_documento_cliente_msg']</value>
      <webElementGuid>7909ad8a-2318-48e6-8b9d-d883565a3e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/div</value>
      <webElementGuid>45e79f64-2018-45c0-9305-bcf81fa09f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[3]</value>
      <webElementGuid>7734e237-85c4-4ddc-8d8c-37e1dc7e5d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[3]</value>
      <webElementGuid>c59beb8c-dcbe-4aa0-9d0b-3b3ffe0921eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola,'])[1]/preceding::div[4]</value>
      <webElementGuid>af75317c-1fcc-4f7a-9e52-bd99f2f46fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Dónde te encuentras?'])[1]/preceding::div[10]</value>
      <webElementGuid>1e5277ea-bbdc-4cff-93a7-77744fc79023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El DNI debe tener 8 dígitos']/parent::*</value>
      <webElementGuid>112a8fed-e0cc-4e22-b91e-36649361fdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/div</value>
      <webElementGuid>39fb4fff-cac8-4e5d-ac17-8d5a5842dee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_documento_cliente_msg' and (text() = 'El DNI debe tener 8 dígitos' or . = 'El DNI debe tener 8 dígitos')]</value>
      <webElementGuid>31d8b562-a97d-4eaf-b4d8-4c00a6a9e73d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
