<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Ingresar un Nmero Documento</name>
   <tag></tag>
   <elementGuidId>398195b7-0ed0-4548-93f1-a9cb79953813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_documento_cliente_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bdc7b211-64f6-4161-9d57-33d5ced3f38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente_msg</value>
      <webElementGuid>7de8a8c6-dafe-4bba-ac03-bed175c4c375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>5889fab6-6f29-4093-9407-edb8e1bcf3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Ingresar un Número Documento</value>
      <webElementGuid>cf0101ac-9c0b-449f-a542-8385fe264737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente_msg&quot;)</value>
      <webElementGuid>56571dee-fe7f-494a-b88b-dd17bf9dbacf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_documento_cliente_msg']</value>
      <webElementGuid>7545593f-8527-400e-aec0-7698adc0f978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/div</value>
      <webElementGuid>97f2fb95-080e-4ad0-ab4f-7dbe874c58a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe seleccionar un tipo de documento'])[1]/following::div[3]</value>
      <webElementGuid>81893be7-00c7-4468-865f-2ec8bfcfece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[4]</value>
      <webElementGuid>af15fe1e-9880-4d50-a24b-7f1b2f04f266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese 9 digitos'])[1]/preceding::div[1]</value>
      <webElementGuid>45f66a21-f1a5-449d-9306-c42dae6b613e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese número de celular'])[1]/preceding::div[2]</value>
      <webElementGuid>a9a70943-b702-49b9-bf55-7bbd372c9327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/div</value>
      <webElementGuid>5b5ea62c-d0ff-432a-8e76-fa2d491c0a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_documento_cliente_msg' and (text() = 'Debe Ingresar un Número Documento' or . = 'Debe Ingresar un Número Documento')]</value>
      <webElementGuid>4e5b846e-4660-4e2a-88e0-465f30f97322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
