<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Seleccionar Tienda</name>
   <tag></tag>
   <elementGuidId>09ab05a8-bbaa-4a73-8b4a-9457c011fbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_tienda_caja_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbo_tienda_caja_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32eac9fc-09f6-4d95-a6bb-67ef14303c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_tienda_caja_msg</value>
      <webElementGuid>94909fde-2f44-4770-b2f3-a1c29cb9f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>f17709d5-1741-45fc-9174-bb93a73d4c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Seleccionar Tienda</value>
      <webElementGuid>02d9e697-9fc6-4a51-a71c-1e6f6cead079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_tienda_caja_msg&quot;)</value>
      <webElementGuid>86368254-74a0-4cb9-84df-48bd080c92f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_tienda_caja_msg']</value>
      <webElementGuid>fa4754b2-daa1-4234-b17b-47450af2bd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>30819319-3d6b-4c00-99e2-dfda9ac9ec0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/following::div[1]</value>
      <webElementGuid>4eabc177-f660-4b4a-b6d5-35e0a4f07589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/following::div[3]</value>
      <webElementGuid>11ce6025-0b6f-48ef-955d-0982868280aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe escribir 4 números'])[1]/preceding::div[1]</value>
      <webElementGuid>d5ee7c08-86f8-479c-9db6-949a66706a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::div[7]</value>
      <webElementGuid>205747c0-0280-4c4e-8816-b58109c0b968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe Seleccionar Tienda']/parent::*</value>
      <webElementGuid>2eb89341-7f97-47cd-a3ce-867b946a86b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>48abd082-d90c-4e03-85f0-f26519cc93d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_tienda_caja_msg' and (text() = 'Debe Seleccionar Tienda' or . = 'Debe Seleccionar Tienda')]</value>
      <webElementGuid>609395da-e467-47b8-8811-88e5edf3cdd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
