<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Selecionar Provincia</name>
   <tag></tag>
   <elementGuidId>347f9f04-5731-4994-8f01-ec4474f12dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_tienda_prov_caja_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbo_tienda_prov_caja_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc6f7884-5abe-470a-be27-30cf9922ec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_tienda_prov_caja_msg</value>
      <webElementGuid>54a77b45-0b9e-4a10-96a9-5773ad0c4d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>2c7c53cf-98d2-453a-ab01-936b99033986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Selecionar Provincia</value>
      <webElementGuid>00b677a2-6d23-4c32-be36-608cff9ce5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_tienda_prov_caja_msg&quot;)</value>
      <webElementGuid>397d3362-37e6-4a2d-b1d7-7b3895fc93c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_tienda_prov_caja_msg']</value>
      <webElementGuid>cf617b11-199f-42ff-9f59-74b3fe90f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[2]/div[3]/div[2]</value>
      <webElementGuid>8141e218-3344-4b90-904a-0d9111f59a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - ATALAYA - ATALAYA'])[2]/following::div[1]</value>
      <webElementGuid>a312bfc4-a591-462b-9916-5a9da9d7e301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PURUS - PURUS'])[2]/following::div[1]</value>
      <webElementGuid>ccd2b57a-971c-4c55-987e-73121ed30291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[2]/preceding::div[1]</value>
      <webElementGuid>6c6be162-6946-491d-a4ca-4c2264f57f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[3]/preceding::div[2]</value>
      <webElementGuid>7da3e8bc-e4d5-41fb-908b-e0be69690b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe Selecionar Provincia']/parent::*</value>
      <webElementGuid>53f427c3-be61-4aad-bb40-127c6b33f0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>8db25cb2-6912-4e5d-bd70-5a99305be7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_tienda_prov_caja_msg' and (text() = 'Debe Selecionar Provincia' or . = 'Debe Selecionar Provincia')]</value>
      <webElementGuid>5cd8b663-9712-4429-aa6e-f99b05ea68d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
