<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OLVA SURCO - AV. EL POLO 108 - SANTIA_b82c80</name>
   <tag></tag>
   <elementGuidId>af3ac64a-0e3e-44fd-946b-1f21942bcc09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_clave_seguridad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_clave_seguridad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82bff450-89ea-4fe2-8ad8-e9636134c3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8020131b-907c-40f7-ab05-f2c58e4f163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>786dacfe-61c2-4843-b91a-3592a4c99ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Clave de seguridad</value>
      <webElementGuid>165cf3e4-c904-4017-969a-13f58a346bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputRE</value>
      <webElementGuid>42c6c118-1231-4f12-bc73-677440570dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_clave_seguridad</value>
      <webElementGuid>536ec5a8-7aa2-4ec6-9ee0-dca34c640786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clave de seguridad</value>
      <webElementGuid>87a566e9-31cc-4efc-807f-0f5903f7bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>569bb593-ec74-469e-af90-4e6638eb42a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8a933b92-e59e-45f2-a01e-dec85c83916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_clave_seguridad&quot;)</value>
      <webElementGuid>e2d680aa-04c5-4741-ab98-0a9ba5f07bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_clave_seguridad']</value>
      <webElementGuid>91a6133a-0a6e-4d85-b17d-ab25aa9b0841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[4]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>eda3d06e-f606-4ddb-988a-38025b1f234d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>550fe366-9821-4e09-86c9-fa1df7e22735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_clave_seguridad' and @placeholder = 'Clave de seguridad' and @id = 'txt_clave_seguridad' and @title = 'Clave de seguridad' and @type = 'text']</value>
      <webElementGuid>d023ba0e-dd8c-49f9-9ee7-045c62d53918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
