<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_compras por internet_expiry</name>
   <tag></tag>
   <elementGuidId>98d3ceca-8518-4e9f-bda9-cfef10e7c305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60d87858-91d3-4123-a8da-23fe0f4c36e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6f6c7250-138a-4e02-bff8-7f562bac01bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>3a5a4cc9-b404-4330-8a0a-ce699f50aea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>0e79085d-50f1-465a-b02c-5aaf95493535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/AA</value>
      <webElementGuid>88bef3b5-a985-4666-bca7-bff35312e0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>5fdb2e4d-6554-4189-8cdf-661941701336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Comprar Empaques/Page_Olva Courier  Datos Personales/iframe_Aceptar_visaNetJS</value>
      <webElementGuid>983850ce-83fc-4b55-b4fb-b85b54251581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>dfecb0fe-7539-4175-ac49-13ad1ece0669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default']/div[5]/div/section/label/input</value>
      <webElementGuid>0e75b55a-9f73-4f52-b8fd-54363fa2507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/section/label/input</value>
      <webElementGuid>f20e18a6-e261-4a5d-8b90-9a3a26bed66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'expiry' and @id = 'expiry' and @placeholder = 'MM/AA']</value>
      <webElementGuid>ec1d4131-65c5-4c7c-a037-de93d278bdc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
