<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT_txt_documento_cliente</name>
   <tag></tag>
   <elementGuidId>3abcc94e-d261-48da-9d9d-9a49a87e8530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_documento_cliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>398624d5-8819-416f-9e5d-cee05a8fee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f49d2b6-27d9-4ab0-be5f-86c07253d210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>324a2a6c-a162-4333-b205-1fde43a4f420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateDNI()</value>
      <webElementGuid>df7e35ca-8949-4036-9c8f-769c2055de8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>fe1da144-fea9-4b0a-b2a7-af094f3752ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>2b30a43c-38ca-422c-8b71-784b89dcf925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número</value>
      <webElementGuid>3a0e4886-f88b-459f-8603-de7497dc683b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control msg_alert_tt</value>
      <webElementGuid>80b75511-4066-465c-8a16-8c33cc228536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>9691102b-803d-404a-8cc8-af6ee5185594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>02ce3cf6-1f27-4a44-b92c-5af569cb33e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>c4fca859-822e-443e-aafa-d6f2719e0ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c0a4309f-ade5-4cff-a4b1-21fb4174cf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente&quot;)</value>
      <webElementGuid>6070971b-64b9-4f54-a9b9-916c6994ab15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_documento_cliente']</value>
      <webElementGuid>32598d46-add0-4eb9-97a4-6457e23ca3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/input</value>
      <webElementGuid>58599548-b4a5-4728-811a-18701eb0d003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>114d7c23-eb6f-4262-9c72-a3381540e649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_documento_cliente' and @placeholder = 'Número' and @title = '.' and @id = 'txt_documento_cliente']</value>
      <webElementGuid>e4fd3a54-bc2b-4307-9795-d7695c9d02fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
