<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El apellido ingresado debe ser igual _544e76</name>
   <tag></tag>
   <elementGuidId>59d7eed7-4071-4fd3-b477-fd5ee089346a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_digito_verificador']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_digito_verificador</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>353709f1-d2a8-4558-8e10-d5e08a1b5a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value> text</value>
      <webElementGuid>71938608-3f64-491d-a587-a78abec1d935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>787ae16e-15bc-4396-9353-ae3feba8f559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>472302d6-6afd-4cca-ab6a-3fc7a6dfb587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>6225719b-d30b-49a9-8314-f30d5a0abc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>INGRESE PRIMER APELLIDO</value>
      <webElementGuid>f3dbe6b1-f885-467c-bbfd-78c02c733b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_digito_verificador&quot;)</value>
      <webElementGuid>8940d9c0-89c6-482c-bb2d-26fe98e539b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_digito_verificador']</value>
      <webElementGuid>d1b26a15-74d7-4fa6-8028-50ebd051da00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>5df26ece-339a-4bc6-ab52-383f79f0f400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>d2c6de6c-f6a3-4e1f-b2f5-22612351f879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = ' text' and @id = 'txt_digito_verificador' and @name = 'txt_digito_verificador' and @placeholder = 'INGRESE PRIMER APELLIDO']</value>
      <webElementGuid>701a2ea3-11c8-437d-a01b-4931fc683b8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
