<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAGAR</name>
   <tag></tag>
   <elementGuidId>dcea60a5-3c31-4f3a-870c-2124acd61dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-tottem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-tottem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18970af6-ef27-40a7-adfc-473171aa67fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-tottem</value>
      <webElementGuid>3082031d-4905-4a87-82a5-31f66956d908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-pagar btn-pagar-2</value>
      <webElementGuid>6800fb7e-f80c-43be-ac9e-5e2a0ad05c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PagarJS.activarPOS()</value>
      <webElementGuid>815ac51c-e5ab-46d5-9675-6714a8f0c55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGAR</value>
      <webElementGuid>09dd3e3f-19fa-4c39-a553-9d8b48eded71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-tottem&quot;)</value>
      <webElementGuid>b6a3b788-0fd6-45ab-812f-e84d15745af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-tottem']</value>
      <webElementGuid>45c6b071-7faa-497b-8305-e05432d5d994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagarTottem']/button</value>
      <webElementGuid>7bf15dba-f7ee-486e-9389-5a5b05db9c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/following::button[1]</value>
      <webElementGuid>8e5e6886-2e61-4d5c-be03-ff6ae3ef7a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 16.50'])[1]/following::button[2]</value>
      <webElementGuid>120b29f2-3583-4c1b-9321-631ee060e394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[2]/preceding::button[1]</value>
      <webElementGuid>2c62ae9c-2b3b-4ab3-a908-3a53ff3381e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[3]/preceding::button[3]</value>
      <webElementGuid>6e085f90-ee86-4be9-93ed-75b8c122f5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAGAR']/parent::*</value>
      <webElementGuid>989d7936-a604-448b-8407-fd62f6843b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div[2]/button</value>
      <webElementGuid>73094a09-85f9-422d-87b8-9cdf1abffb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-tottem' and (text() = 'PAGAR' or . = 'PAGAR')]</value>
      <webElementGuid>ca9fc036-225a-48c0-ba70-f8d3fd4a3cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
