<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ingrese el ancho del paquete</name>
   <tag></tag>
   <elementGuidId>f56b6414-7e9b-4238-94db-5936f5514f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-input-ancho_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-input-ancho_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4772f763-1eaa-4d40-b41d-cdc80febeb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-input-ancho_msg</value>
      <webElementGuid>ad27d933-f60d-46e5-a7c4-9398b3c55d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error col-md-offset-1</value>
      <webElementGuid>e6fea54a-ac61-43c2-8413-f141c7ac7ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingrese el ancho del paquete</value>
      <webElementGuid>882ba1e9-dccc-4777-873b-9516dc4e8f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-input-ancho_msg&quot;)</value>
      <webElementGuid>ffaeaaef-3164-4ac0-81e4-d896064ce9b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modal-input-ancho_msg']</value>
      <webElementGuid>3a5950d5-128a-415b-ab61-868cecb5b9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPesoDimensiones']/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>23788c28-a51e-40e3-a142-412c9550a259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ancho (cm)'])[1]/following::div[1]</value>
      <webElementGuid>89a20243-beed-4457-b6ee-bde6b11d07d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[10]/following::div[10]</value>
      <webElementGuid>7e63d23d-a9e7-49ae-ae24-0bba5db045fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Largo (cm)'])[1]/preceding::div[1]</value>
      <webElementGuid>ffb5c3b8-72e2-43bd-b9fa-3f6d5efdb8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese el largo del paquete'])[1]/preceding::div[1]</value>
      <webElementGuid>a8608dc2-3fbf-44ab-b2e5-364a6e34c4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ingrese el ancho del paquete']/parent::*</value>
      <webElementGuid>560b5002-221b-4da6-a9dc-b27711ebe3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>c3917a81-9f93-4868-bcd0-da394d913c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'modal-input-ancho_msg' and (text() = 'Ingrese el ancho del paquete' or . = 'Ingrese el ancho del paquete')]</value>
      <webElementGuid>57cbd04d-fed2-4b97-b85c-41bebf1253ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
