<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CALCULAR</name>
   <tag></tag>
   <elementGuidId>55aa72c6-0c89-43ab-90b5-b3bec84a0aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_calcular']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_calcular</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efa0d073-7597-4e55-a340-1f67e3c10a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-yellow-selected ml-10</value>
      <webElementGuid>40467fab-3c54-4ee5-84b0-91bdce23bbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_calcular</value>
      <webElementGuid>cc6fa278-ca11-4f3f-a1b5-62df9d217432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CALCULAR</value>
      <webElementGuid>d1b03979-65f4-4ac8-b796-937c417401fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_calcular&quot;)</value>
      <webElementGuid>226a3375-6f1f-4cc4-814e-ab5944164e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_calcular']</value>
      <webElementGuid>eef6d110-4aec-4032-b6af-466dbd4b77bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPesoDimensiones']/div/div/div[2]/center/div</value>
      <webElementGuid>eb25807a-4723-4aee-bc8b-8a0de11a08ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso (Kg)'])[1]/following::div[2]</value>
      <webElementGuid>fafb8ef2-065b-4fd0-8861-56df66c9d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alto (cm)'])[1]/following::div[3]</value>
      <webElementGuid>3457fdfb-cdfb-4f46-aff9-7a2d15e949ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::div[2]</value>
      <webElementGuid>75b289eb-1b3c-4fb5-b3c9-ee22c6b3fc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando...'])[2]/preceding::div[12]</value>
      <webElementGuid>7a3593dc-34ac-48bc-b0c9-b4948a6c0c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CALCULAR']/parent::*</value>
      <webElementGuid>3ff7e7e1-bf59-421c-8fab-daac68cd7c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/center/div</value>
      <webElementGuid>7fa1ab97-4a3b-4b30-86c8-78cc19252f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_calcular' and (text() = 'CALCULAR' or . = 'CALCULAR')]</value>
      <webElementGuid>42d34c5c-3184-40e4-bd47-33ea0ba0d104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
