<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No encuentro el peso de mi envo</name>
   <tag></tag>
   <elementGuidId>35f8bbe0-fae4-4e58-aa57-372c3e0ba2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_peso_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_peso_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46e5f16b-0528-4f29-b3bb-b9980766e61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 border-yellow ml-10</value>
      <webElementGuid>6b1669d7-9e23-4176-bf57-bd67df5667fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_peso_0</value>
      <webElementGuid>f964ad1d-9873-46ae-ba32-5fe7b42edc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No encuentro el peso de mi envío</value>
      <webElementGuid>0a37f2ad-e803-4f56-9904-ed5076e4208e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_peso_0&quot;)</value>
      <webElementGuid>17b91ee7-0bab-4f2b-9dcf-98485a13bc99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_peso_0']</value>
      <webElementGuid>1bd00b1e-d9e7-424b-bff6-f06c8955695f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_peso_inferior']/div[3]</value>
      <webElementGuid>966c79c0-805e-4717-afdb-a7f4c68e377d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kg'])[1]/preceding::div[1]</value>
      <webElementGuid>5e25d321-bdc3-49f1-bfbb-f41f216410b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No encuentro el peso de mi envío']/parent::*</value>
      <webElementGuid>d6a52173-54b1-4bda-86d1-b30049befaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]</value>
      <webElementGuid>19168098-a3c4-4baa-82a7-8a1edff4a863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div_peso_0' and (text() = 'No encuentro el peso de mi envío' or . = 'No encuentro el peso de mi envío')]</value>
      <webElementGuid>44a88258-8d5d-4fbf-bbb2-f38be944e3e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
