<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Largo (cm)_modal-input-largo</name>
   <tag></tag>
   <elementGuidId>65ac8107-ac1b-48e3-ad45-41ba784f09f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modal-input-largo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-input-largo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4aacc0f-1b8e-448e-acdf-fcf7ab33837d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>67d948b7-8142-44e5-bad4-69fb47174264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-input-largo</value>
      <webElementGuid>a035170b-bdd7-444b-aaed-d12d15ef5ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-yellow-peso-dimension col-md-12 col-sm-12 col-xs-12</value>
      <webElementGuid>1b5f0f99-5386-4519-a237-4bab8f36ef79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej. 14</value>
      <webElementGuid>eb1d1079-2b3c-4519-9cee-e4ea457bb504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-input-largo&quot;)</value>
      <webElementGuid>3533f498-2b74-404f-8d91-35664f8290fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modal-input-largo']</value>
      <webElementGuid>7b1d7fca-1f80-4f58-bd10-1c0d05084db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPesoDimensiones']/div/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>631b740b-a5d4-4d33-b9ba-8cd0b4267601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>b1170acf-5ba0-4466-a754-de4151f75b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'modal-input-largo' and @placeholder = 'Ej. 14']</value>
      <webElementGuid>3aabab90-c768-4beb-acae-fff43fad8b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
