<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alto (cm)_modal-input-alto</name>
   <tag></tag>
   <elementGuidId>d972665d-404b-466e-b0a9-e476fbf6a40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modal-input-alto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-input-alto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>498d1b27-85c4-4e72-b882-fe6c31592d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d9d87d03-2612-4a24-8dfe-fce65726a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-input-alto</value>
      <webElementGuid>4752d68d-d4bb-4d82-8713-c853675a18c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-yellow-peso-dimension col-md-12 col-sm-12 col-xs-12</value>
      <webElementGuid>f854b471-107e-4635-9373-0aee4876675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej. 14</value>
      <webElementGuid>8769673b-7152-4b36-9635-b0ad5e500da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-input-alto&quot;)</value>
      <webElementGuid>8dd825b1-0d69-42ed-ac8f-2c687c8472c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modal-input-alto']</value>
      <webElementGuid>58481026-bb38-435a-8270-e44dd8f21fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPesoDimensiones']/div/div/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>2d9f2f57-b0c9-48a1-8e09-7067128030cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>932bab21-e64a-4a1e-92d4-19dc904ba1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'modal-input-alto' and @placeholder = 'Ej. 14']</value>
      <webElementGuid>1b865cf8-894c-4440-8f0b-00a9b4b296cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
