<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe seleccionar un artculo de la lista</name>
   <tag></tag>
   <elementGuidId>da370526-55dc-4dc6-a287-faa32221e4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbo_paquete_idarticulo_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cbo_paquete_idarticulo_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>248d4867-2143-4fb5-b05e-3da85271034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbo_paquete_idarticulo_msg</value>
      <webElementGuid>e7b6dbfe-50c8-4017-8bc0-e94ac7be7e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>97c4f8af-fd7d-4d4d-b444-7776bbf8f7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe seleccionar un artículo de la lista</value>
      <webElementGuid>fc43cb05-d0c6-40d7-b435-70111ea715bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbo_paquete_idarticulo_msg&quot;)</value>
      <webElementGuid>5bb7e2c7-bedf-45e0-badf-3190c4dbb8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cbo_paquete_idarticulo_msg']</value>
      <webElementGuid>aa446f2c-fbf9-449e-a713-141420af9c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo']/div[2]</value>
      <webElementGuid>f12a020f-0f43-4bb4-b14d-d33ec94e2ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILES DE OFICINA'])[2]/following::div[1]</value>
      <webElementGuid>ebb81067-822f-4392-86f3-f0649a1ae8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILES DE ESCRITORIO'])[2]/following::div[1]</value>
      <webElementGuid>c5a080cd-2ad6-4ce5-a6d7-b9e48f6d2f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debe ingresar la descripción del artículo'])[1]/preceding::div[1]</value>
      <webElementGuid>48f1547e-64bd-4322-acb5-6379e406d294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese un valor al articulo'])[1]/preceding::div[3]</value>
      <webElementGuid>6a8536aa-9dfc-4ed4-ba9f-38d66bec1a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe seleccionar un artículo de la lista']/parent::*</value>
      <webElementGuid>f51bec56-ce7d-49ac-a72f-1d87928bbccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div[2]</value>
      <webElementGuid>7772ad73-c972-4d15-8812-23233f04cb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cbo_paquete_idarticulo_msg' and (text() = 'Debe seleccionar un artículo de la lista' or . = 'Debe seleccionar un artículo de la lista')]</value>
      <webElementGuid>e0d881a1-5e0e-450d-b228-0fc99315f7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
