<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Debe Seleccionar el Destino</name>
   <tag></tag>
   <elementGuidId>d5a3820e-be53-4901-9218-8444ce72eb23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txt_descripcion_ubigeo_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_descripcion_ubigeo_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>244e72e2-25fb-49ec-bf16-6de3bf7d612d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_descripcion_ubigeo_msg</value>
      <webElementGuid>6205a267-6006-475a-bc68-2ad866531e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl_msg_error</value>
      <webElementGuid>091e0010-34af-4888-8f86-fbb5719994c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debe Seleccionar el Destino</value>
      <webElementGuid>5334ec5f-f192-4eb4-82ad-a73afb564d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_descripcion_ubigeo_msg&quot;)</value>
      <webElementGuid>bf1f5249-6c20-4560-8315-bbb7027334bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txt_descripcion_ubigeo_msg']</value>
      <webElementGuid>2153c0ad-a6bd-451a-a875-491cf9bfb085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_origen_destino']/div/div[3]/div/div/div[2]</value>
      <webElementGuid>29931278-258c-4032-835f-ff4c6bda1b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PURUS - PURUS'])[2]/following::div[1]</value>
      <webElementGuid>39b5bcfa-be67-4902-af7a-6ae29d54f287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UCAYALI - PADRE ABAD - NESHUYA'])[2]/following::div[1]</value>
      <webElementGuid>44aa6d1b-87c2-4047-9b83-fe627e27ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese el punto de llegada'])[5]/preceding::div[1]</value>
      <webElementGuid>79620f7a-3067-4a4b-b1f9-7eb12bf77e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese el punto de llegada'])[6]/preceding::div[2]</value>
      <webElementGuid>86801443-36d5-4b86-b3d5-91d18b4c62e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Debe Seleccionar el Destino']/parent::*</value>
      <webElementGuid>82cb8313-6e6e-40e2-890e-18d6d3dd5b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/div/div[2]</value>
      <webElementGuid>bae6173d-e21e-4482-bcc8-a9364ab49db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txt_descripcion_ubigeo_msg' and (text() = 'Debe Seleccionar el Destino' or . = 'Debe Seleccionar el Destino')]</value>
      <webElementGuid>adedb665-71c9-4b3f-a219-ce6e17b5c1d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
