<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAGAR</name>
   <tag></tag>
   <elementGuidId>81ac6fcc-bbe4-4d85-b2ef-eadeebd30aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-tottem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-tottem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bebb09c9-fa9f-4e4c-a551-b1c54fbf5e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-tottem</value>
      <webElementGuid>42d24a59-eed1-4fa0-ba32-2d3cfdc6f1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-pagar btn-pagar-2</value>
      <webElementGuid>9867c937-b08b-4dc8-b0aa-789a3021d8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PagarJS.activarPOS()</value>
      <webElementGuid>a90afde2-b561-4a73-b5a6-3a882da309dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGAR</value>
      <webElementGuid>de006bcf-96e9-4eab-bb2e-51fa449c6915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-tottem&quot;)</value>
      <webElementGuid>51d757c6-5205-4507-9d40-e6dd8f7f9afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-tottem']</value>
      <webElementGuid>2d8d9446-7994-4b6c-9366-4423b256532b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagarTottem']/button</value>
      <webElementGuid>672d7b6e-e023-4f55-bc59-58cf0cb041c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/following::button[1]</value>
      <webElementGuid>4d47d52a-ab63-4507-8701-66a51c761adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 18.60'])[1]/following::button[2]</value>
      <webElementGuid>7c762554-7991-4202-ae0d-fa4a642bcd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[2]/preceding::button[1]</value>
      <webElementGuid>597a0db0-8aab-47f6-bc0f-b313fbddee31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGAR'])[3]/preceding::button[3]</value>
      <webElementGuid>6904c653-1254-49f3-bde6-77a57c604c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAGAR']/parent::*</value>
      <webElementGuid>cdf6ef1a-13d5-4d3a-99f1-8dc13de85698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div[2]/button</value>
      <webElementGuid>713cf614-aa0d-48af-a17e-611cc5ec32ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-tottem' and (text() = 'PAGAR' or . = 'PAGAR')]</value>
      <webElementGuid>df4ebda9-ba59-4adc-9b62-d2b4334cc4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
