<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de cajas o paquetescon un peso mxi_37770f</name>
   <tag></tag>
   <elementGuidId>66c49bb6-146f-49fa-9e41-23f3c41df949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_sobre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9644afb5-5e06-4b9e-a80e-5a540ba2f85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_sobre</value>
      <webElementGuid>1858d809-9791-4a3e-9664-dd13b24cdb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png</value>
      <webElementGuid>7266085f-5ffe-4207-9b17-81691aecfc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>27f51613-323f-4866-a040-3ea63eed55cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>432d190d-b5c4-424b-8b6f-90a60a6b44ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>9605260f-c3fa-4afc-8deb-bcfd6d2ae4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_sobre&quot;)</value>
      <webElementGuid>5d09d2ff-194a-4b67-bcb6-c3c3ab0e6690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_sobre']</value>
      <webElementGuid>7cdd95f5-379b-4c70-9f30-04da509d9f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_sobre']/img</value>
      <webElementGuid>5e11eda8-e2bd-4d49-8b87-d10a2c99fbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN PAQUETE'])[1]/following::img[1]</value>
      <webElementGuid>b3d923d8-2e3b-4de1-9af5-df9f626d17a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN SOBRE'])[1]/preceding::img[1]</value>
      <webElementGuid>0805140c-7521-470e-af8a-e0a289f80203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png')]</value>
      <webElementGuid>cf9913a9-a731-4ebe-bfc2-a61ef324f481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/div/figure/img</value>
      <webElementGuid>950ef574-6a35-4ac4-83f1-d8e73e7f8ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_sobre' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png']</value>
      <webElementGuid>c65613d3-1e8c-4c04-859b-5d526b705d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
