<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Razn Social_txt_razon_social</name>
   <tag></tag>
   <elementGuidId>922df23e-6e6c-46ff-aaf6-92cd8dd696c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_razon_social</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_razon_social']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2399d4af-472d-4046-86e5-6f38b231378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88646615-7ebb-4c8c-b74e-f44418a5e506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputRE</value>
      <webElementGuid>9456b8bc-ee70-473a-ad4d-71cfe022b044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_razon_social</value>
      <webElementGuid>1e87b164-27e4-4e32-bbad-db306d6cbb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8626a88b-3976-4950-96e3-96b66b60dec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RAZÓN SOCIAL</value>
      <webElementGuid>96770af0-49ec-4039-a478-ea59a9dcf858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_razon_social&quot;)</value>
      <webElementGuid>f95fc536-ff0c-4849-a892-9f5c94b62598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_razon_social']</value>
      <webElementGuid>bec5bb82-3aa7-42d4-a7fa-668546f9dfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoCliente']/div/div/div[2]/div[7]/div/input</value>
      <webElementGuid>36958b85-b4a3-43f2-88fe-90619073b4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>f94b4010-f39c-4e65-9f6f-4a1864b9fe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_razon_social' and @placeholder = 'RAZÓN SOCIAL']</value>
      <webElementGuid>7662d1b2-89d3-4a61-b5d3-b5f22d797611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
